import type { Product } from "@/lib/types";

export const aditivos: Product[] = [
  // Z Cron DESMOLDANTE
  {
    id: "pro-zcron-1",
    code: "ZCRON-01",
    name: "Z Cron DESMOLDANTE",
    description: "Desmoldante oleoso de alto rendimiento, libre de VOC, diseñado para facilitar el desencofrado de concreto y mortero en superficies metálicas, fenólicas, plásticas o de madera. Proporciona acabados limpios y sin manchas, optimizando la productividad en obra.",
    price: 0,
    discount: 0,
    rating: 4.5,
    reviews: 30,
    image: "/aditivos/zcron.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-zcron",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Desmoldante oleoso base mineral, libre de VOC",
      "Color": "Ámbar claro",
      "Densidad": "0.86 kg/L (±0.02)",
      "pH": "6.0–6.1",
      "Sólidos Totales": "≈ 82.7 %",
      "Rendimiento": "25–30 m²/galón",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Compatibilidad": "Madera, metal, fenólico, plástico",
      "Punto de inflamación": "> 100°C",
      "Norma": "Cumple ASTM C309"
    },
    features: [
      "Evita la adherencia del concreto al encofrado y facilita el desencofrado",
      "No mancha ni altera el color del concreto",
      "Reduce el desgaste de los moldes y prolonga su vida útil",
      "Fácil de aplicar y de limpiar",
      "No tóxico, seguro para el usuario y el ambiente"
    ],
    fichaTecnica: "https://panel.construproductos.com/filespdf/z-cron-610d3f4661914.pdf",
    tags: ["desmoldante", "encofrado", "aceite", "z-cron", "z aditivos"],
    stockDisponible: 100,
    ubicacionAlmacen: "nuevo chimbote - chimbote"
  },
  // Z Desmol AL
  {
    id: "pro-zdesmolal-1",
    code: "ZDESMOLAL-01",
    name: "Z Desmol AL",
    description: "Desmoldante base aluminio especialmente formulado para evitar la adherencia del concreto a encofrados metálicos y de madera. Garantiza superficies lisas y reduce el desgaste de los moldes, facilitando la limpieza y reutilización.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/zdesmol.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-zdesmolal",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Desmoldante base aluminio",
      "Color": "Transparente",
      "Densidad": "0.85-0.90 kg/L",
      "Rendimiento": "20–30 m²/galón",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Punto de inflamación": "> 100°C",
      "Compatibilidad": "Encofrados metálicos y de madera",
      "Norma": "Cumple ASTM C309"
    },
    features: [
      "Evita la adherencia del concreto al encofrado",
      "Acabado superficial liso y sin manchas",
      "Reduce el desgaste y facilita la limpieza de los moldes",
      "Fácil aplicación y alta eficiencia",
      "No altera la resistencia del concreto"
    ],
    fichaTecnica: "https://perusupply.com/wp-content/uploads/2022/09/FICHA-TECNICA-Z-CRON.pdf",
    tags: ["desmoldante", "aluminio", "encofrado"],
    stockDisponible: 100,
    ubicacionAlmacen: "nuevo chimbote - chimbote"
  },
  // Z Desmolac PU
  {
    id: "pro-zdemolac-1",
    code: "ZDEMOLAC-01",
    name: "Z Desmolac PU",
    description: "Desmoldante de poliuretano de alta eficiencia, ideal para aplicaciones donde se requiere un acabado impecable y rápido desmoldeo. Compatible con todo tipo de encofrados y excelente para piezas arquitectónicas.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/DESMOLAC.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zdemolac",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Desmoldante base poliuretano",
      "Color": "Transparente",
      "Densidad": "0.90 kg/L",
      "Rendimiento": "25 m²/galón",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Punto de inflamación": "> 100°C",
      "Compatibilidad": "Todo tipo de encofrados",
      "Norma": "Cumple ASTM C309"
    },
    features: [
      "Desmoldeo rápido y eficiente",
      "Acabado impecable en piezas arquitectónicas",
      "Compatible con encofrados metálicos, fenólicos y plásticos",
      "No deja residuos ni manchas",
      "Fácil limpieza de moldes"
    ],
    fichaTecnica: "https://www.sika.com/dms/getdocument.get/7e2e2e2e-2e2e-2e2e-2e2e-2e2e2e2e2e2e/sika-release-agent.pdf",
    tags: ["desmoldante", "poliuretano", "encofrado"],
    stockDisponible: 100,
    ubicacionAlmacen: "nuevo chimbote - chimbote"
  },
  // Curadores
  {
    id: "pro-zmembranab-1",
    code: "ZMEMBRANAB-01",
    name: "Z Membrana Blanco",
    description: "Curador líquido de membrana blanca que forma una película protectora sobre el concreto fresco, reduciendo la evaporación del agua y asegurando un curado óptimo. Mejora la resistencia y durabilidad del concreto.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZMEMBRANA.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zmembranaB",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Curador líquido base agua, membrana blanca",
      "Color": "Blanco lechoso",
      "Densidad": "1.00–1.05 kg/L",
      "Rendimiento": "5–7 m²/L",
      "Aplicación": "Aspersión, brocha o rodillo",
      "Tiempo de secado": "1–2 horas",
      "Norma": "ASTM C309, ASTM C156"
    },
    features: [
      "Reduce la evaporación del agua en el concreto fresco",
      "Mejora la resistencia y durabilidad del concreto",
      "Fácil aplicación y rápido secado",
      "Compatible con superficies horizontales y verticales",
      "Minimiza la fisuración superficial"
    ],
    fichaTecnica: "",
    tags: ["curador"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-zmembranas-1",
    code: "ZMEMBRANAS-01",
    name: "Z Membrana S",
    description: "Curador de membrana tipo S, diseñado para conservar la humedad en el concreto durante el proceso de fraguado. Favorece el desarrollo de resistencias y minimiza la fisuración superficial.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZMEMBRANAS.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zmembranas",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Curador líquido base agua, membrana tipo S",
      "Color": "Blanco",
      "Densidad": "1.00–1.05 kg/L",
      "Rendimiento": "5–7 m²/L",
      "Aplicación": "Aspersión, brocha o rodillo",
      "Tiempo de secado": "1–2 horas",
      "Norma": "ASTM C309, ASTM C156"
    },
    features: [
      "Conserva la humedad en el concreto durante el fraguado",
      "Favorece el desarrollo de resistencias",
      "Minimiza la fisuración superficial",
      "Fácil de aplicar",
      "No tóxico"
    ],
    fichaTecnica: "",
    tags: ["curador"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-curetz-1",
    code: "CURETZ-01",
    name: "Curet Z",
    description: "Curador líquido Curet Z, ideal para obras donde se requiere un curado eficiente y uniforme. Protege el concreto de la desecación prematura y mejora la calidad final de la superficie.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/CURETZ.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-curetz",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Curador líquido base agua",
      "Color": "Blanco",
      "Densidad": "1.00–1.05 kg/L",
      "Rendimiento": "5–7 m²/L",
      "Aplicación": "Aspersión, brocha o rodillo",
      "Tiempo de secado": "1–2 horas",
      "Norma": "ASTM C309, ASTM C156"
    },
    features: [
      "Protege el concreto de la desecación prematura",
      "Mejora la calidad superficial",
      "Fácil aplicación",
      "Compatible con concreto estructural y arquitectónico",
      "No altera el color del concreto"
    ],
    fichaTecnica: "",
    tags: ["curador"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Impermeabilizantes - Integrales
  {
    id: "pro-z1liquido-1",
    code: "Z1LIQUIDO-01",
    name: "Z 1 Líquido",
    description: "Aditivo impermeabilizante integral líquido para concreto, que actúa desde el interior de la mezcla, bloqueando la penetración de agua y aumentando la durabilidad de las estructuras.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/BALDE5.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-z1liquido",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo impermeabilizante líquido",
      "Color": "Transparente",
      "Densidad": "1.05–1.10 kg/L",
      "Rendimiento": "0.5–1% del peso del cemento",
      "Aplicación": "Mezclado directo en el concreto",
      "Compatibilidad": "Concreto y mortero",
      "Norma": "ASTM C494, Tipo A"
    },
    features: [
      "Bloquea la penetración de agua desde el interior",
      "Aumenta la durabilidad de las estructuras",
      "No afecta la resistencia del concreto",
      "Fácil dosificación y mezcla",
      "Compatible con otros aditivos"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante", "integral"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-z1polvo-1",
    code: "Z1POLVO-01",
    name: "Z 1 Polvo",
    description: "Impermeabilizante integral en polvo para concreto, formulado para mezclarse fácilmente y brindar protección contra la humedad y agentes agresivos desde el interior de la masa.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Z1POLVO.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-sub2",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo impermeabilizante en polvo",
      "Color": "Gris claro",
      "Densidad": "1.10–1.20 kg/L",
      "Rendimiento": "1% del peso del cemento",
      "Aplicación": "Mezclado directo en seco",
      "Compatibilidad": "Concreto y mortero",
      "Norma": "ASTM C494, Tipo A"
    },
    features: [
      "Protección integral contra humedad y agentes agresivos",
      "Fácil de mezclar con el cemento",
      "No afecta la trabajabilidad",
      "Aumenta la vida útil de la estructura",
      "Compatible con otros aditivos"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante", "integral"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Impermeabilizantes - Estructuras Enterradas
  {
    id: "pro-bitumen-1",
    code: "BITUMEN-01",
    name: "Z Bitumen",
    description: "Impermeabilizante bituminoso de alta adherencia, ideal para proteger estructuras enterradas contra la humedad y agentes químicos del suelo. Forma una barrera continua y flexible.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZSOLVENTEB.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-bitumen",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Impermeabilizante bituminoso",
      "Color": "Negro",
      "Densidad": "1.00–1.10 kg/L",
      "Rendimiento": "1–2 m²/L",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Secado al tacto": "2–4 horas",
      "Norma": "ASTM D41"
    },
    features: [
      "Protege estructuras enterradas contra humedad y químicos",
      "Forma una barrera continua y flexible",
      "Alta adherencia a concreto y mampostería",
      "Fácil aplicación",
      "Resistente a agentes agresivos del suelo"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-imprimantez-1",
    code: "IMPRIMANTEZ-01",
    name: "Imprimante Z",
    description: "Imprimante asfáltico que mejora la adherencia de impermeabilizantes en superficies de concreto o mampostería. Facilita la aplicación y prolonga la vida útil de los sistemas impermeables.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZALQUITRAN.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-imprimantez",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Imprimante asfáltico",
      "Color": "Negro",
      "Densidad": "0.90–1.00 kg/L",
      "Rendimiento": "4–6 m²/L",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Secado al tacto": "1–2 horas",
      "Norma": "ASTM D41"
    },
    features: [
      "Mejora la adherencia de impermeabilizantes",
      "Facilita la aplicación de sistemas asfálticos",
      "Prolonga la vida útil de los sistemas impermeables",
      "Fácil de aplicar",
      "Compatible con concreto y mampostería"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-zsolventeb-1",
    code: "ZSOLVENTEB-01",
    name: "Z Solvente B",
    description: "Solvente especializado para la limpieza y dilución de impermeabilizantes asfálticos, asegurando una aplicación uniforme y óptima penetración en la superficie.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZSOLVENTEB2.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zsolventeb",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Solvente para impermeabilizantes asfálticos",
      "Color": "Transparente",
      "Densidad": "0.80–0.85 kg/L",
      "Rendimiento": "Variable según uso",
      "Aplicación": "Limpieza y dilución",
      "Compatibilidad": "Impermeabilizantes asfálticos"
    },
    features: [
      "Facilita la limpieza de herramientas y equipos",
      "Permite ajustar la viscosidad de impermeabilizantes",
      "Asegura una aplicación uniforme",
      "No deja residuos",
      "Compatible con productos asfálticos"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Impermeabilizantes - Tanques y Cisternas
  {
    id: "pro-aquafin-1",
    code: "AQUAFIN-01",
    name: "Aquafin-CI",
    description: "Impermeabilizante cementicio de alta resistencia, diseñado para proteger tanques y cisternas de concreto contra filtraciones y ataques químicos. Apto para contacto con agua potable.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/aquafinic.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-aquafin",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Impermeabilizante cementicio bicomponente",
      "Color": "Gris claro",
      "Densidad": "1.60–1.80 kg/L",
      "Rendimiento": "1.5–2 kg/m²",
      "Aplicación": "Brocha, llana o rodillo",
      "Resistencia a presión de agua": "> 5 bar",
      "Norma": "EN 1504-2"
    },
    features: [
      "Protege tanques y cisternas contra filtraciones",
      "Apto para agua potable",
      "Alta resistencia química y mecánica",
      "Flexible y duradero",
      "Fácil aplicación"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-ztopimpermeable-1",
    code: "ZTOPIMPERMEABLE-01",
    name: "Z Top Impermeable",
    description: "Revestimiento impermeable flexible, ideal para tanques y cisternas que requieren máxima protección contra el paso del agua y movimientos estructurales.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Z-TOP-IMPERMEABLE.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-ztopimpermeable",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Revestimiento impermeable flexible",
      "Color": "Gris",
      "Densidad": "1.50–1.70 kg/L",
      "Rendimiento": "1.5–2 kg/m²",
      "Aplicación": "Brocha, llana o rodillo",
      "Resistencia a presión de agua": "> 5 bar",
      "Norma": "EN 1504-2"
    },
    features: [
      "Máxima protección contra el paso del agua",
      "Flexible, soporta movimientos estructurales",
      "Excelente adherencia a concreto y mampostería",
      "Durabilidad superior",
      "Fácil de aplicar"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-ztopflexible-1",
    code: "ZTOPFLEXIBLE-01",
    name: "Z Top Flexible",
    description: "Impermeabilizante bicomponente flexible, formulado para proteger superficies sometidas a presión de agua y movimientos. Excelente adherencia y durabilidad en tanques y cisternas.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ztopflexible22.jfif",
    category: "z-aditivo",
    subcategory: "z-aditivo-ztopflexible",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Impermeabilizante bicomponente flexible",
      "Color": "Gris",
      "Densidad": "1.60–1.80 kg/L",
      "Rendimiento": "1.5–2 kg/m²",
      "Aplicación": "Brocha, llana o rodillo",
      "Resistencia a presión de agua": "> 5 bar",
      "Norma": "EN 1504-2"
    },
    features: [
      "Protección flexible para tanques y cisternas",
      "Soporta presión de agua y movimientos",
      "Excelente adherencia y durabilidad",
      "Fácil aplicación",
      "Apto para agua potable"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Impermeabilizantes - Superficiales
  {
    id: "pro-zimperoof-1",
    code: "ZIMPEROOf-01",
    name: "Z Imperoof",
    description: "Impermeabilizante superficial de aplicación directa, ideal para proteger losas, terrazas y superficies expuestas a la intemperie. Forma una barrera resistente al agua y rayos UV.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/IMPEROOF---Z.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zimperoof",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Impermeabilizante superficial acrílico",
      "Color": "Blanco",
      "Densidad": "1.20–1.30 kg/L",
      "Rendimiento": "1–1.5 kg/m²",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Resistencia a rayos UV": "Alta",
      "Norma": "ASTM D6083"
    },
    features: [
      "Forma una barrera resistente al agua y rayos UV",
      "Ideal para losas y terrazas expuestas",
      "Flexible y duradero",
      "Fácil aplicación",
      "Alta reflectancia solar"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-z2000-1",
    code: "Z2000-01",
    name: "Z 2000",
    description: "Impermeabilizante superficial Z 2000, diseñado para sellar y proteger superficies de concreto contra la penetración de agua y agentes agresivos del ambiente.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Z2000-NUEVOLOGO.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-z2000",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Impermeabilizante superficial acrílico",
      "Color": "Blanco",
      "Densidad": "1.20–1.30 kg/L",
      "Rendimiento": "1–1.5 kg/m²",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Resistencia a rayos UV": "Alta",
      "Norma": "ASTM D6083"
    },
    features: [
      "Sella y protege superficies de concreto",
      "Resistente a la intemperie y rayos UV",
      "Fácil de aplicar",
      "Durabilidad prolongada",
      "No altera el color del sustrato"
    ],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Impermeabilizantes - Sellador de Superficies
  {
    id: "pro-matez-1",
    code: "MATEZ-01",
    name: "Mate Z",
    description: "Sellador acrílico de alto desempeño, ideal para proteger superficies de concreto y mampostería, realzando el acabado y facilitando la limpieza.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/MATEZ5GAL.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-matez",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Sellador acrílico base agua",
      "Color": "Transparente",
      "Densidad": "1.00–1.05 kg/L",
      "Rendimiento": "8–10 m²/L",
      "Aplicación": "Brocha, rodillo o aspersión",
      "Secado al tacto": "1 hora",
      "Norma": "ASTM C309"
    },
    features: [
      "Protege y realza el acabado de superficies de concreto",
      "Facilita la limpieza y el mantenimiento",
      "Alta resistencia a la abrasión",
      "No amarillea con el tiempo",
      "Fácil aplicación"
    ],
    fichaTecnica: "",
    tags: ["sellador"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Selladores de Juntas
  {
    id: "pro-zflex3040-1",
    code: "ZFLEX3040-01",
    name: "Z Flex PU 30-40",
    description: "Sellador elástico de poliuretano, especialmente formulado para juntas de dilatación y construcción en pisos y muros. Alta resistencia a movimientos y agentes químicos.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/zflex3040.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-zflex3040",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Sellador elástico de poliuretano",
      "Color": "Gris",
      "Dureza Shore A": "30–40",
      "Movimiento permitido": "±25%",
      "Rendimiento": "Variable según ancho de junta",
      "Aplicación": "Pistola calafatera",
      "Norma": "ASTM C920"
    },
    features: [
      "Alta elasticidad y resistencia química",
      "Ideal para juntas de dilatación y construcción",
      "Excelente adherencia a concreto y mampostería",
      "Durabilidad superior",
      "Fácil aplicación"
    ],
    fichaTecnica: "",
    tags: ["sellador", "juntas"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-imprimantezpm-1",
    code: "IMPRIMANTEZPM-01",
    name: "Imprimante ZPM",
    description: "Imprimante promotor de adherencia para selladores de juntas, mejora la fijación y durabilidad del sellado en superficies porosas o difíciles.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/IMPRIMANTE-ZPM-430x430.jpeg",
    category: "z-aditivo",
    subcategory: "z-aditivo-imprimantezpm",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Imprimante promotor de adherencia",
      "Color": "Transparente",
      "Densidad": "0.90–1.00 kg/L",
      "Rendimiento": "10–12 m²/L",
      "Aplicación": "Brocha o rodillo",
      "Secado al tacto": "30 minutos"
    },
    features: [
      "Mejora la adherencia de selladores en superficies porosas",
      "Fácil de aplicar",
      "Secado rápido",
      "Compatible con selladores de poliuretano y epóxicos",
      "Aumenta la durabilidad del sellado"
    ],
    fichaTecnica: "",
    tags: ["sellador", "juntas"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-zflexpoliuretano-1",
    code: "ZFLEXPOLIURETANO-01",
    name: "Z Flex Poliuretano A+B",
    description: "Sellador bicomponente de poliuretano, ideal para juntas sometidas a movimientos y exposición a agentes agresivos. Excelente elasticidad y durabilidad.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Z-FLEX-POLIURETANO-GRIS-1-GAL.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-zflexpoliuretano",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Sellador bicomponente de poliuretano",
      "Color": "Gris",
      "Dureza Shore A": "40–50",
      "Movimiento permitido": "±25%",
      "Rendimiento": "Variable según ancho de junta",
      "Aplicación": "Pistola calafatera",
      "Norma": "ASTM C920"
    },
    features: [
      "Excelente elasticidad y resistencia química",
      "Ideal para juntas sometidas a movimientos",
      "Durabilidad y vida útil prolongada",
      "Fácil aplicación",
      "Adherencia superior"
    ],
    fichaTecnica: "",
    tags: ["sellador", "juntas"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-backerrod-1",
    code: "BACKERROD-01",
    name: "Backer Rod",
    description: "Espuma de polietileno Backer Rod, utilizada como fondo de junta para controlar la profundidad y optimizar el consumo de sellador en aplicaciones de juntas de expansión.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/backerrod1.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-backerrod",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Espuma de polietileno de celda cerrada",
      "Color": "Gris",
      "Densidad": "25–35 kg/m³",
      "Diámetro": "6–50 mm",
      "Temperatura de servicio": "-40°C a 90°C",
      "Compatibilidad": "Selladores de poliuretano, silicona y epóxicos"
    },
    features: [
      "Controla la profundidad de la junta",
      "Optimiza el consumo de sellador",
      "Flexible y fácil de instalar",
      "No absorbe agua",
      "Compatible con múltiples selladores"
    ],
    fichaTecnica: "",
    tags: ["sellador", "juntas"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Selladores para juntas frías
  {
    id: "pro-waterpvc-1",
    code: "WATERPVC-01",
    name: "Water Stop PVC",
    description: "Perfil de PVC flexible para sellado de juntas frías en estructuras de concreto, previniendo filtraciones y asegurando la estanqueidad de la obra.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/gsc_126678029_4649790_148x20ddd.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-waterpvc",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Perfil de PVC flexible",
      "Color": "Azul/Negro",
      "Dureza Shore A": "70–80",
      "Ancho": "150–300 mm",
      "Temperatura de servicio": "-20°C a 60°C",
      "Compatibilidad": "Concreto estructural"
    },
    features: [
      "Previene filtraciones en juntas frías",
      "Flexible y fácil de instalar",
      "Alta resistencia química",
      "Durabilidad prolongada",
      "Asegura la estanqueidad de la estructura"
    ],
    fichaTecnica: "",
    tags: ["sellador", "juntas frías"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-waterrx101-1",
    code: "WATERRX101-01",
    name: "Water Stop RX-101",
    description: "Perfil hidroexpansivo RX-101, diseñado para sellar juntas frías en concreto, expandiéndose al contacto con el agua y garantizando un sellado hermético.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/images.jfif",
    category: "z-aditivo",
    subcategory: "z-aditivo-waterrx101",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Perfil hidroexpansivo de caucho",
      "Color": "Negro",
      "Dureza Shore A": "50–60",
      "Expansión volumétrica": "> 300% al contacto con agua",
      "Temperatura de servicio": "-20°C a 60°C",
      "Compatibilidad": "Concreto estructural"
    },
    features: [
      "Sella juntas frías mediante expansión al contacto con agua",
      "Fácil de instalar",
      "Alta durabilidad y resistencia química",
      "Asegura sellado hermético",
      "Compatible con concreto y mortero"
    ],
    fichaTecnica: "",
    tags: ["sellador", "juntas frías"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Epóxicos
  {
    id: "pro-pox31-1",
    code: "POX31-01",
    name: "Z Pox 31",
    description: "Resina epóxica de alta resistencia, ideal para reparaciones estructurales, anclajes y protección de superficies de concreto sometidas a cargas elevadas.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZPOX315KG1.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-pox31",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Resina epóxica bicomponente",
      "Color": "Transparente/Ámbar",
      "Densidad": "1.10–1.20 kg/L",
      "Resistencia a compresión": "> 70 MPa",
      "Tiempo de curado": "24 horas",
      "Aplicación": "Brocha, llana o inyección",
      "Norma": "ASTM C881"
    },
    features: [
      "Alta resistencia mecánica y química",
      "Ideal para reparaciones estructurales y anclajes",
      "Excelente adherencia a concreto y acero",
      "Fácil de aplicar",
      "Durabilidad superior"
    ],
    fichaTecnica: "",
    tags: ["epoxico"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-pox32-1",
    code: "POX32-01",
    name: "Z Pox 32",
    description: "Epóxico de dos componentes, formulado para brindar máxima adherencia y resistencia química en reparaciones y recubrimientos industriales.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/610d4828e7c7d.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-pox32",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Epóxico bicomponente",
      "Color": "Gris",
      "Densidad": "1.10–1.20 kg/L",
      "Resistencia a compresión": "> 70 MPa",
      "Tiempo de curado": "24 horas",
      "Aplicación": "Brocha, llana o inyección",
      "Norma": "ASTM C881"
    },
    features: [
      "Máxima adherencia y resistencia química",
      "Ideal para recubrimientos industriales",
      "Fácil de aplicar",
      "Durabilidad prolongada",
      "Compatible con concreto y acero"
    ],
    fichaTecnica: "",
    tags: ["epoxico"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-poxbv-1",
    code: "POXBV-01",
    name: "Z Pox BV",
    description: "Epóxico Z Pox BV, diseñado para aplicaciones donde se requiere alta resistencia mecánica y protección contra agentes agresivos.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/610d4828e7c7d222.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-poxbv",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Epóxico bicomponente",
      "Color": "Gris",
      "Densidad": "1.10–1.20 kg/L",
      "Resistencia a compresión": "> 70 MPa",
      "Tiempo de curado": "24 horas",
      "Aplicación": "Brocha, llana o inyección",
      "Norma": "ASTM C881"
    },
    features: [
      "Alta resistencia mecánica y química",
      "Protección contra agentes agresivos",
      "Fácil aplicación",
      "Durabilidad superior",
      "Compatible con concreto y acero"
    ],
    fichaTecnica: "",
    tags: ["epoxico"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-poxtacha-1",
    code: "POXTACHA-01",
    name: "Z Pox Tacha",
    description: "Epóxico Z Pox Tacha, especial para anclajes y fijaciones en concreto, proporcionando máxima durabilidad y resistencia a la vibración.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Z-TACHAS.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-poxtacha",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Epóxico bicomponente para anclajes",
      "Color": "Gris",
      "Densidad": "1.10–1.20 kg/L",
      "Resistencia a compresión": "> 70 MPa",
      "Tiempo de curado": "24 horas",
      "Aplicación": "Brocha, llana o inyección",
      "Norma": "ASTM C881"
    },
    features: [
      "Especial para anclajes y fijaciones",
      "Máxima durabilidad y resistencia a vibraciones",
      "Fácil de aplicar",
      "Compatible con concreto y acero",
      "Curado rápido"
    ],
    fichaTecnica: "",
    tags: ["epoxico"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Separadores
  {
    id: "pro-separadores2-1",
    code: "SEPARADORES2-01",
    name: "Separadores de Concreto",
    description: "Separadores plásticos para concreto, ideales para mantener el recubrimiento adecuado de las armaduras y garantizar la durabilidad de la estructura.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/1718197714qDTMwXeY.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-separadores2",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Separador plástico para concreto",
      "Color": "Gris",
      "Material": "Polipropileno",
      "Resistencia a compresión": "> 200 kg",
      "Diámetro": "10–50 mm",
      "Compatibilidad": "Concreto armado"
    },
    features: [
      "Mantiene el recubrimiento adecuado de armaduras",
      "Fácil de instalar",
      "Alta resistencia a compresión",
      "No absorbe agua",
      "Durabilidad prolongada"
    ],
    fichaTecnica: "",
    tags: ["epoxico", "separador"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Morteros - Reparación
  {
    id: "pro-morterot40-1",
    code: "MORTEROT40-01",
    name: "Mortero Z T40",
    description: "Mortero de reparación estructural, formulado para restaurar elementos de concreto dañados, ofreciendo alta adherencia y resistencia mecánica.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Morterot40.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-morterot40",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Mortero de reparación estructural",
      "Color": "Gris",
      "Densidad": "2.00–2.20 kg/L",
      "Resistencia a compresión": "> 45 MPa",
      "Tiempo de fraguado": "2–4 horas",
      "Aplicación": "Espátula, llana o molde",
      "Norma": "EN 1504-3"
    },
    features: [
      "Alta adherencia y resistencia mecánica",
      "Ideal para restaurar elementos dañados",
      "Fácil aplicación",
      "Durabilidad superior",
      "Compatible con concreto estructural"
    ],
    fichaTecnica: "",
    tags: ["mortero", "reparacion"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Morteros - Nivelación
  {
    id: "pro-znivelante-1",
    code: "ZNIVELANTE-01",
    name: "Z Nivelante T30",
    description: "Mortero autonivelante de fraguado rápido, ideal para nivelar superficies antes de la colocación de revestimientos o acabados finales.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/T30-23KG-20231012002946.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-znivelante",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Mortero autonivelante de fraguado rápido",
      "Color": "Gris claro",
      "Densidad": "1.80–2.00 kg/L",
      "Resistencia a compresión": "> 30 MPa",
      "Tiempo de fraguado": "1–2 horas",
      "Aplicación": "Vertido y nivelado",
      "Norma": "EN 13813"
    },
    features: [
      "Nivelación rápida y precisa de superficies",
      "Fácil de aplicar y extender",
      "Alta resistencia mecánica",
      "Compatible con revestimientos y acabados",
      "Durabilidad prolongada"
    ],
    fichaTecnica: "",
    tags: ["mortero", "nivelacion"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Morteros - Endurecedor de piso
  {
    id: "pro-zpiso-1",
    code: "ZPISO-01",
    name: "Z Piso",
    description: "Endurecedor mineral para pisos industriales, incrementa la resistencia al desgaste y prolonga la vida útil de superficies sometidas a tráfico intenso.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZPISO25KG.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zpiso",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Endurecedor mineral para pisos",
      "Color": "Gris",
      "Densidad": "2.20–2.40 kg/L",
      "Resistencia a abrasión": "Alta",
      "Aplicación": "Espolvoreo y fratasado",
      "Norma": "ASTM C779"
    },
    features: [
      "Incrementa la resistencia al desgaste",
      "Prolonga la vida útil de pisos industriales",
      "Fácil aplicación",
      "Compatible con concreto fresco",
      "Alta resistencia a la abrasión"
    ],
    fichaTecnica: "",
    tags: ["mortero", "endurecedor"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Morteros - Groutings
  {
    id: "pro-zgrout-1",
    code: "ZGROUT-01",
    name: "Z Grout",
    description: "Grout cementicio de alta fluidez, diseñado para relleno de placas base, anclajes y fijaciones en estructuras de concreto.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Z-GROUT.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zgrout",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Grout cementicio de alta fluidez",
      "Color": "Gris",
      "Densidad": "2.10–2.30 kg/L",
      "Resistencia a compresión": "> 60 MPa",
      "Tiempo de fraguado": "2–4 horas",
      "Aplicación": "Vertido y relleno",
      "Norma": "ASTM C1107"
    },
    features: [
      "Alta fluidez para relleno de placas base y anclajes",
      "Rápido desarrollo de resistencias",
      "Fácil aplicación",
      "Durabilidad superior",
      "Compatible con concreto estructural"
    ],
    fichaTecnica: "",
    tags: ["mortero", "grout"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-morteroepoxicosz-1",
    code: "MORTEROEPOXICOSZ-01",
    name: "Mortero Epoxicos Z",
    description: "Mortero epóxico de tres componentes, ideal para reparaciones estructurales y anclajes que requieren máxima resistencia química y mecánica.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/MORTEROEPOXICOC.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-morteroepoxicosz",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Mortero epóxico de tres componentes",
      "Color": "Gris",
      "Densidad": "1.80–2.00 kg/L",
      "Resistencia a compresión": "> 70 MPa",
      "Tiempo de fraguado": "2–4 horas",
      "Aplicación": "Espátula, llana o molde",
      "Norma": "ASTM C881"
    },
    features: [
      "Máxima resistencia química y mecánica",
      "Ideal para anclajes y reparaciones estructurales",
      "Fácil de aplicar",
      "Durabilidad prolongada",
      "Compatible con concreto y acero"
    ],
    fichaTecnica: "",
    tags: ["mortero", "epoxico"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Aditivos para concreto - Plastificantes y Superplastificantes
  {
    id: "pro-zfluidizanteir-1",
    code: "ZFLUIDIZANTEIR-01",
    name: "Z Fluidizante IR",
    description: "Aditivo plastificante para concreto, mejora la trabajabilidad y reduce el consumo de agua, permitiendo mezclas más fluidas y resistentes.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Copia-de-Z-FLUIDIZANTE-IR-5GAL.jpg",
    category: "z-aditivo",
    subcategory: "z-aditivo-zfluidizanteir",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo plastificante líquido",
      "Color": "Marrón",
      "Densidad": "1.10–1.20 kg/L",
      "Rendimiento": "0.5–1% del peso del cemento",
      "Aplicación": "Mezclado directo en el concreto",
      "Norma": "ASTM C494, Tipo A"
    },
    features: [
      "Mejora la trabajabilidad del concreto",
      "Reduce el consumo de agua",
      "Aumenta la resistencia final",
      "Fácil dosificación y mezcla",
      "Compatible con otros aditivos"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "plastificante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-zrrplast545-1",
    code: "ZRRPLAST545-01",
    name: "Z RR Plast 545",
    description: "Superplastificante de alto rendimiento, incrementa la fluidez del concreto y permite obtener resistencias elevadas con menor relación agua/cemento.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZRRPLAST5GAL.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zrrplast545",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Superplastificante líquido",
      "Color": "Marrón oscuro",
      "Densidad": "1.10–1.20 kg/L",
      "Rendimiento": "0.5–1% del peso del cemento",
      "Aplicación": "Mezclado directo en el concreto",
      "Norma": "ASTM C494, Tipo F"
    },
    features: [
      "Incrementa la fluidez del concreto",
      "Permite obtener resistencias elevadas",
      "Reduce la relación agua/cemento",
      "Fácil de mezclar",
      "Compatible con otros aditivos"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "superplastificante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-zfluidizantesr1000-1",
    code: "ZFLUIDIZANTESR1000-01",
    name: "Z Fluidizante SR-1000",
    description: "Aditivo plastificante de nueva generación, optimiza la colocación del concreto y mejora la cohesión de la mezcla.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/ZFLUIDIZANTEZR1000.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zfluidizantesr1000",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo plastificante de nueva generación",
      "Color": "Marrón",
      "Densidad": "1.10–1.20 kg/L",
      "Rendimiento": "0.5–1% del peso del cemento",
      "Aplicación": "Mezclado directo en el concreto",
      "Norma": "ASTM C494, Tipo A"
    },
    features: [
      "Optimiza la colocación del concreto",
      "Mejora la cohesión de la mezcla",
      "Fácil dosificación y mezcla",
      "Compatible con otros aditivos",
      "Aumenta la resistencia final"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "plastificante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Aditivos para concreto - Acelerantes
  {
    id: "pro-zfragua3-1",
    code: "ZFRAGUA3-01",
    name: "Z Fragua #3",
    description: "Aditivo acelerante de fraguado, ideal para obras en climas fríos o donde se requiere rápida puesta en servicio del concreto.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/images(1).jfif",
    category: "z-aditivo",
    subcategory: "z-aditivo-zfragua3",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo acelerante de fraguado",
      "Color": "Transparente",
      "Densidad": "1.20–1.30 kg/L",
      "Rendimiento": "1–2% del peso del cemento",
      "Aplicación": "Mezclado directo en el concreto",
      "Norma": "ASTM C494, Tipo C"
    },
    features: [
      "Acelera el fraguado del concreto",
      "Ideal para climas fríos o trabajos urgentes",
      "No afecta la resistencia final",
      "Fácil de dosificar",
      "Compatible con otros aditivos"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "acelerante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-zfragua5-1",
    code: "ZFRAGUA5-01",
    name: "Z Fragua #5",
    description: "Aditivo acelerante de alta eficiencia, reduce el tiempo de fraguado y permite desencofrar o transitar sobre el concreto en menor tiempo.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/images(2).jfif",
    category: "z-aditivo",
    subcategory: "z-aditivo-zfragua5",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo acelerante de alta eficiencia",
      "Color": "Transparente",
      "Densidad": "1.20–1.30 kg/L",
      "Rendimiento": "1–2% del peso del cemento",
      "Aplicación": "Mezclado directo en el concreto",
      "Norma": "ASTM C494, Tipo C"
    },
    features: [
      "Reduce el tiempo de fraguado",
      "Permite desencofrar o transitar antes",
      "No afecta la resistencia final",
      "Fácil de dosificar",
      "Compatible con otros aditivos"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "acelerante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Aditivos para concreto - Retardantes
  {
    id: "pro-zretar-1",
    code: "ZRETAR-01",
    name: "Z Retar",
    description: "Aditivo retardante de fraguado, prolonga el tiempo de trabajabilidad del concreto y previene juntas frías en colados extensos.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/images(3).jfif",
    category: "z-aditivo",
    subcategory: "z-aditivo-zretar",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo retardante de fraguado",
      "Color": "Transparente",
      "Densidad": "1.10–1.20 kg/L",
      "Rendimiento": "0.5–1% del peso del cemento",
      "Aplicación": "Mezclado directo en el concreto",
      "Norma": "ASTM C494, Tipo B"
    },
    features: [
      "Prolonga el tiempo de trabajabilidad del concreto",
      "Previene juntas frías en colados extensos",
      "No afecta la resistencia final",
      "Fácil de dosificar",
      "Compatible con otros aditivos"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "retardante"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  // Aditivos para concreto - Complementarios
  {
    id: "pro-zresina100-1",
    code: "ZRESINA100-01",
    name: "Z Resina 100%",
    description: "Aditivo líquido de resina acrílica, mejora la adherencia y flexibilidad de morteros y concretos, ideal para reparaciones y refuerzos.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/Z-RESINA-100.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zresina100%",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Aditivo líquido de resina acrílica",
      "Color": "Blanco lechoso",
      "Densidad": "1.00–1.05 kg/L",
      "Rendimiento": "0.5–1% del peso del cemento",
      "Aplicación": "Mezclado directo en mortero o concreto",
      "Norma": "ASTM C1059"
    },
    features: [
      "Mejora la adherencia y flexibilidad de morteros y concretos",
      "Ideal para reparaciones y refuerzos",
      "Fácil de mezclar",
      "Compatible con cemento y cal",
      "No altera el color del mortero"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "complementario"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-removedoroxido-1",
    code: "REMOVEDOROXIDO-01",
    name: "Removedor de Óxido",
    description: "Removedor de óxido de acción rápida, elimina eficazmente la corrosión en superficies metálicas antes de pintar o recubrir.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/REMOVEDORDEOXIDO5GAL.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-removedoroxido",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Removedor de óxido líquido",
      "Color": "Transparente",
      "Densidad": "1.00–1.05 kg/L",
      "Rendimiento": "Variable según uso",
      "Aplicación": "Brocha o inmersión",
      "Compatibilidad": "Superficies metálicas"
    },
    features: [
      "Elimina eficazmente la corrosión en superficies metálicas",
      "Acción rápida y profunda",
      "Fácil de aplicar",
      "No deja residuos",
      "Compatible con pinturas y recubrimientos"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "complementario"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
  {
    id: "pro-zfibrapp-1",
    code: "ZFIBRAPP-01",
    name: "Z Fibra PP",
    description: "Fibra de polipropileno para refuerzo de concreto, reduce la fisuración por retracción y mejora la durabilidad de la mezcla.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/aditivos/fibrazpp-LOGO.png",
    category: "z-aditivo",
    subcategory: "z-aditivo-zfibrapp",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {
      "Tipo": "Fibra de polipropileno para refuerzo",
      "Color": "Blanco",
      "Longitud": "6–18 mm",
      "Densidad": "0.91 g/cm³",
      "Resistencia a tracción": "> 400 MPa",
      "Compatibilidad": "Concreto y mortero"
    },
    features: [
      "Reduce la fisuración por retracción",
      "Mejora la durabilidad del concreto",
      "Fácil de mezclar",
      "No altera la trabajabilidad",
      "Compatible con todo tipo de mezclas"
    ],
    fichaTecnica: "",
    tags: ["aditivo", "complementario"],
    stockDisponible: 0,
    ubicacionAlmacen: "",
  },
];
