import type { Product } from "@/lib/types";

export const baldosasProducts: Product[] = [
    {
        id: "26544789",
        code: "SKY730101",
        name: "BALDOSA DE VINIL GYSUM 60 X 60 (CJX10)",
        description: "Baldosa Gypsum Vinyl con revestimiento de vinyl por un lado, brinda una alta reflexión de la luz y es fácil de limpiar.",
        price: 0,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/baldosa/baldosa154.jpg",
        category: "cielo-raso",
        subcategory: "baldosavinil",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Placa de Yeso laminado con Vinyl y foil de Aluminio",
            Espesor: "7mm",
            Modulacion: "2´x 2´ (60 x 60 cm)",
            Peso: "5.50 Kg/ m2 (aprox.)",
            Color: "Blanco",
        },
        features: [
            "Ligero, resistente y estable, ideal para cielos rasos interiores.",
            "Fácil de cortar y soldarCompatible con sistemas de cielo raso modular.",
            "Gracias a la lámina de aluminio, mantiene su forma frente a cambios de temperatura y humedad.",
        ],
        fichaTecnica: "",
        tags: ["baldosa", "vinil", "gypsum"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "2654472322",
        code: "SKY7301066",
        name: "BALDOSAS CONSTRUTEK 1.22 x 0.61 m",
        description: "Baldosas Construtek es un sistema de cielo raso modular de fibra mineral que juntas ofrecen los más altos niveles de absorción y aislamiento acústico.",
        price: 0,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/baldosa/baldosasconstru.jpg",
        category: "cielo-raso",
        subcategory: "baldosacosntrutek",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Fibra Mineral moldeada en húmedo",
            Espesor: "12mm",
            Modulacion: "1.22 x 0.61 m",
            Peso: "5.50 Kg/ m2 (aprox.)",
            Color: "Blanco",
        },
        features: [
            "Las baldosas Construtek tienen un excelente acabado arquitectónico.",
            "Son elegantes y pueden ser usadas en distintos ambientes.",
            "El producto no es tóxico, sin asbesto.",
        ],
        fichaTecnica: "",
        tags: ["baldosa", "fibra mineral", "cosntrutek"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "2654472322",
        code: "SKY730105567",
        name: "BALDOSAS FIBROCEMENTO 0.61 x 0.61 m",
        description: "La baldosa de fibrocemento es una solución robusta y confiable para cielos rasos interiores y exteriores. Fabricada a base de cemento reforzado con fibras minerales, ofrece alta resistencia a la humedad, al fuego y a los impactos, sin deformarse ni deteriorarse con el paso del tiempo.",
        price: 0,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/baldosa/baldosafibrocemento.jpg",
        category: "cielo-raso",
        subcategory: "baldosafibrocemento",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Fibrocemento",
            Espesor: "4mm",
            Modulacion: "0.61 x 0.61 m",
            Peso: "5.50 Kg/ m2 (aprox.)",
            Color: "Blanco",
        },
        features: [
            "Las baldosas fibrocemento tienen un excelente acabado arquitectónico.",
            "Son elegantes y pueden ser usadas en distintos ambientes.",
            "El producto no es tóxico, sin asbesto.",
        ],
        fichaTecnica: "",
        tags: ["baldosa", "fibrocemento", "fibrocemento"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
];
