import type { Product } from "@/lib/types";

export const chemaProducts: Product[] = [
  // IMPERMEABILIZANTES INTEGRALES
  {
    id: "chema-1-liquido-1",
    code: "CHEMA1LIQ-01",
    name: "Chema 1 Líquido",
    description: "Aditivo impermeabilizante integral para concreto y mortero.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/CHEMA1.jpg",
    category: "chema",
    subcategory: "chema-1-liquido",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: { "Tipo": "Líquido", "Uso": "Concreto y mortero" },
    features: ["Reduce permeabilidad", "Fácil de usar"],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chema-1-polvo-1",
    code: "CHEMA1POLVO-01",
    name: "Chema 1 en polvo",
    description: "Aditivo impermeabilizante en polvo para concreto y mortero.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/CHEMA1-POLVO.jpg",
    category: "chema",
    subcategory: "chema-1-polvo",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: { "Tipo": "Polvo", "Uso": "Concreto y mortero" },
    features: ["Impermeabilización eficiente"],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chemita-polvo-1",
    code: "CHEMITAPOLVO-01",
    name: "Chemita en polvo",
    description: "Aditivo impermeabilizante en polvo para mortero.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/CHEMITA-EN-POLVO.jpg",
    category: "chema",
    subcategory: "chemita-polvo",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: { "Tipo": "Polvo", "Uso": "Mortero" },
    features: ["Fácil dosificación"],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chemaplast-impermeabilizante-1",
    code: "CHEMAPLASTIMP-01",
    name: "Chemaplast Impermeabilizante",
    description: "Aditivo impermeabilizante para concreto y mortero.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/chemaplast-impermeabilizante-1.jpg",
    category: "chema",
    subcategory: "chemaplast-impermeabilizante",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: { "Tipo": "Líquido", "Uso": "Concreto y mortero" },
    features: ["Alta compatibilidad"],
    fichaTecnica: "",
    tags: ["impermeabilizante"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  // IMPERMEABILIZANTES SUPERFICIALES
  {
    id: "chemaantisalitre-1",
    code: "CHEMAANTISALITRE-01",
    name: "Chema Antisalitre Extreme",
    description: "Impermeabilizante superficial para protección contra salitre.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/CHEMA-WELD-1G-300x300.jpg",
    category: "chema",
    subcategory: "chemaantisalitre",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chematopantisalitre-1",
    code: "CHEMATOPANTISALITRE-01",
    name: "Chema Top Antisalitre Tipo Pintura",
    description: "Impermeabilizante superficial tipo pintura para muros y fachadas.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/ChemaTopPintura.webp",
    category: "chema",
    subcategory: "chematopantisalitre",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chematop-1",
    code: "CHEMATOP-01",
    name: "Chema Top en Polvo",
    description: "Impermeabilizante superficial en polvo para superficies de concreto.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/chematop.jfif",
    category: "chema",
    subcategory: "chematop",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chema-seal-1",
    code: "CHEMASEAL-01",
    name: "Chema Seal",
    description: "Impermeabilizante superficial para sellado de superficies.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/WEB-Chema-Seal.png",
    category: "chema",
    subcategory: "chema-seal",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chema-seal-200-1",
    code: "CHEMASEAL200-01",
    name: "Chema Seal 200",
    description: "Impermeabilizante superficial de alto desempeño.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/chema-seal-200-2-600x600.jpg",
    category: "chema",
    subcategory: "chema-seal-200",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chema-seal-por-cristalizacion-1",
    code: "CHEMASEALCRISTAL-01",
    name: "Chema Seal por Cristalizacion",
    description: "Impermeabilizante superficial por cristalización para concreto.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/WEB-Chema-Seal(1).png",
    category: "chema",
    subcategory: "chema-seal-por-cristalizacion",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chematecho-1",
    code: "CHEMATECHO-01",
    name: "Chema Techo",
    description: "Impermeabilizante superficial para techos.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/Chema-Techo-web.jpg",
    category: "chema",
    subcategory: "chematecho",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chematechoelastic-1",
    code: "CHEMATECHOELASTIC-01",
    name: "Chema Techo Elastic",
    description: "Impermeabilizante elástico para techos.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/CHEMA-TECHO-ELASTIC.jpg",
    category: "chema",
    subcategory: "chematechoelastic",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chema-bitumen-1",
    code: "CHEMABITUMEN-01",
    name: "Chema Bitumen",
    description: "Impermeabilizante bituminoso para superficies.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/Chema-Bitumen.png",
    category: "chema",
    subcategory: "chema-bitumen",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "chema-alquitran-1",
    code: "CHEMAALQUITRAN-01",
    name: "Chema Alquitran",
    description: "Impermeabilizante a base de alquitrán para superficies.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/images.jfif",
    category: "chema",
    subcategory: "chema-alquitran",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "water-stop-1",
    code: "WATERSTOP-01",
    name: "Water Stop",
    description: "Impermeabilizante para juntas y grietas.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/Chema-Water-Stop.webp",
    category: "chema",
    subcategory: "water-stop",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  },
  {
    id: "water-stop-de-pvc-1",
    code: "WATERSTOPPVC-01",
    name: "Water Stop de PVC",
    description: "Impermeabilizante de PVC para juntas de dilatación.",
    price: 0,
    discount: 0,
    rating: 0,
    reviews: 0,
    image: "/chema/water-stop-pvc.jpg",
    category: "chema",
    subcategory: "water-stop-de-pvc",
    isNew: true,
    inStock: true,
    date: "2025-06-27",
    technicalSpecs: {},
    features: [],
    fichaTecnica: "",
    tags: ["impermeabilizante", "superficial"],
    stockDisponible: 0,
    ubicacionAlmacen: ""
  }
];
