import type { Product } from "@/lib/types";

export const inalambricas: Product[] = [ 
    {
        id: "22334432",
        code: "ATORIMPAC01",
        name: "ATORNILLADOR DE IMPACTO / LI-ION 20V / HEX:6.35 230NM / 2X2.AHM / 0-2900BPM / BRUSHLESS  /TOTAL",
        description: "Atornillador de Impacto Total TIRLI2023 con motor Brushless, encastre 1/4'', torque máximo de 230 Nm, velocidad variable y diseño compacto para uso profesional.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/inalambricos/atornilladorimpacto.webp",
        images: [
            "/inalambricos/atornilladorimpacto.webp",
            "/total/total-img-produc1.webp",
            "/total/total-img-produc2.webp",
        ],
        category: "inalámbricas",
        subcategory: "impacto",
        isNew: true,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Motor: "sin carbones ",
            Voltaje: "20V",
            Encastre: "1/4 (6.35mm)",
            Batería: "2.0Ah",  
            Velocidad:" 0-2000/0-2400/0-2600rpm",
            Impacto: "0-2100/0-2500/0-2900bpm",
            Torque: "230Nm",
            Luz: "trabajo LED integrada",
          
        },
        features: [
            "2pz puntas para atormillar",
            "2 baterías de 2.0Ah",
            "1 cargador",
            "voltaje de 220-240V~50/60Hz",
            "luz de trabajo LED integrada",
        ],
        fichaTecnica: "",
        tags: ["atornillador","Total","taladros","inalámbricos","herramientas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "22309494",
        code: "ATORIMPAC02",
        name: "TALADRO PERCUTOR COMPACTO LI.ON 20V 55NM 13MM BRUSHLESS INDUSTRIAL /TOTAL",
        description: "Taladro percutor Total TIDLI205581, torque de 55 Nm, ideal para trabajos industriales con potencia y rendimiento profesional.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/inalambricos/tadro-percutor.webp",
        images: [
            "/inalambricos/tadro-percutor.webp",
            "/total/total-img-produc1.webp",
            "/total/total-img-produc2.webp",
        ],
        category: "inalámbricas",
        subcategory: "taladro",
        isNew: true,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Motor: "sin carbones ",
            Voltaje: "20V",
            Encastre: "1/4 (6.35mm)",
            Batería: "2.0Ah",  
            Velocidad:" 0-500/0-2000 rpm",
            Impacto: "30000 bpm",
            Torque: "55NM",
            Luz: "trabajo LED integrada",
            Indica:"LED de batería Si",
          
        },
        features: [
            "1pz puntas para atormillar",
            "3pz brocas de acero",
            "Sin batería",
        ],
        fichaTecnica: "",
        tags: ["atornillador","Total","taladros","inalámbricos","herramientas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },{
        id: "2230949423",
        code: "TAGLI21154",
        name: "AMOLADORA ESMERIL INALAMBRICA 4-1/2' DE 20V BRUSHLESS 3000-9000 RPM INDUSTRIAL M14 - TOTAL",
        description: "Amoladora inalámbrica Total de 4-1/2'' (115 mm), con motor Brushless de alto rendimiento, velocidad variable de 3000 a 9000 RPM, rosca M14 y diseño industrial para corte y desbaste eficiente en metal, concreto y más.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/inalambricos/amoladoratotal.webp",
        images: [
            "/inalambricos/amoladoratotal.webp",
            "/total/total-img-produc1.webp",
            "/total/total-img-produc2.webp",
        ],
        category: "inalámbricas",
        subcategory: "amoladora-inalambrica",
        isNew: true,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Marca: "Total",
            Modelo: "TAGLI2001",
            Tipo: "Amoladora angular inalámbrica",
            disco: "4-1/2'' (115 mm)",
            Voltaje: "20V",
            Motor: "Brushless (sin carbones)",
            Velocidad: "3000 – 9000 RPM",
            Rosca: "M14",
            Uso: "Industrial",
            Bateria: "Compatible con sistema Total P20S (no incluida)",
            Empuñadura: "Antideslizante, diseño ergonómico",
            Proteccióna: "Sí"       
        },
        features: [
           "Motor Brushless que reduce el desgaste y prolonga la vida útil.",
           "Velocidad variable para adaptarse a diferentes materiales y tareas.",
           "Diseño compacto, resistente y fácil de maniobrar.",
           "Compatible con toda la línea Total P20S.",
           "Ideal para cortes, desbaste y trabajos de precisión en metal, concreto y cerámica."
        ],
        fichaTecnica: "",
        tags: ["amoladora inalámbrica", "esmeril Total 20V", "herramienta brushless", "amoladora 4-1/2 M14", "esmeril industrial", "amoladora sin cable"," Total TAGLI2001", "herramientas Total P20S", "amoladora para metal", "amoladora drywall", "esmeril cerámica"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },{
        id: "2233453",
        code: "PCAL01",
        name: "PISTOLA DE CALOR / LI-ION 20V / 300-550C° 100-200 L/MIN + ACC MALETIN / INDUSTRIAL  / TOTAL",
        description: "Pistola de calor inalámbrica Total de 20V, ideal para trabajos industriales de termorretracción, soldado, pintura y más. Rango de temperatura de 300 a 550 °C y flujo de aire de 100–200 L/min. Incluye maletín y accesorios.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/inalambricos/pistola-calor-total.webp",
        images: [
            "/inalambricos/pistola-calor-total.webp",
            "/total/total-img-produc1.webp",
            "/total/total-img-produc2.webp",
        ],
        category: "inalámbricas",
        subcategory: "pistola-calor",
        isNew: true,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Marca: "Total",
            Modelo: "THGLI2001",
            Tipo: "Pistola de calor inalámbrica",
            Voltaje: "20V (Li-Ion)",
            Temperatura: "300 °C – 550 °C",
            FlujoAire: "100 – 200 L/min",
            Uso: "Industrial",
            Bateria: "Compatible con sistema Total P20S (no incluida)",
            Accesorios:"Incluye boquillas y maletín de transporte",     
        },
        features: [
           "Rango amplio de temperatura ideal para múltiples aplicaciones.",
           "Funcionamiento inalámbrico con tecnología Li-Ion de 20V.",
           "Incluye accesorios y maletín para transporte y organización.",
           "Flujo de aire potente y estable.",
           "Compatible con toda la línea de baterías Total P20S.",
           "Diseño industrial para trabajo continuo y exigente."
        ],
        fichaTecnica: "",
        tags: ["pistola de calor inalámbrica", "herramienta Total 20V", "pistola de calor industrial", "THGLI2001", "herramienta para termorretracción", "pistola de calor sin cable", "Total P20S", "pistola calor drywall", "remover pintura", "pistola de aire caliente"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },



]