import type { Product } from "@/lib/types";

export const masillasProducts: Product[] = [
    {
        id: "223456",
        code: "126032",
        name: "Masilla, Gyplac Cajas de 20KG ",
        description: "La Masilla Gyplac es el complemento ideal para lograr un excelente acabado de junta invisible, luego de instalar las placas de yeso Gyplac en paredes y cielos rasos interiores. Este producto es fabricado de acuerdo con la norma ASTM C475/C475M.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masilla20kg.jpg",
        category: "materiales",
        subcategory: "masillasG20",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "24cm",
            Ancho:"26cm",
            Dimensiones: "20cm",
            Color: "Blanco",
            Peso: "20kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Masilla en pasta, lista para usar. ",
            "Formulada de resinas e insumos de alta calidad para una excelente adherencia, trabajabilidad y textura final. ",
            "Fácil de aplicar, perfecto acabado, excelente adherencia, menor riesgo de fisuras y super llenado.",
            "Este producto es fabricado de acuerdo con la norma ASTM C475/C475M."
        ],
        fichaTecnica: "https://etex.azureedge.net/pi780262/original/789466626/ft-masilla-en-pasta-gyplac-20kg_setiembre-2024.pdf",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "223454",
        code: "403108",
        name: "MASILLA BALDE 27 KG / GYPLAC",
        description: "La Masilla Gyplac es el complemento ideal para lograr un excelente acabado de junta invisible, luego de instalar las placas de yeso Gyplac en paredes y cielos rasos interiores. Este producto es fabricado de acuerdo con la norma ASTM C475/C475M.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masillabalde.webp",
        category: "masillas",
        subcategory: "masillasG27",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "40cm",
            Ancho:"30cm",
            Profundidad:"30cm",
            Color: "Blanco",
            Peso: "27kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Masilla en pasta, lista para usar. ",
            "Formulada de resinas e insumos de alta calidad para una excelente adherencia, trabajabilidad y textura final. ",
            "Fácil de aplicar, perfecto acabado, excelente adherencia, menor riesgo de fisuras y super llenado.",
            "Este producto es fabricado de acuerdo con la norma ASTM C475/C475M."
        ],
        fichaTecnica: "https://etex.azureedge.net/pi780262/original/789466626/ft-masilla-en-pasta-gyplac-20kg_setiembre-2024.pdf",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
     {
        id: "2234566",
        code: "410396",
        name: "MASILLA 5KG / GYPLAC",
        description: "La Masilla Gyplac es el complemento ideal para lograr un excelente acabado de junta invisible, luego de instalar las placas de yeso Gyplac en paredes y cielos rasos interiores. Este producto es fabricado de acuerdo con la norma ASTM C475/C475M.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masilla5kg.webp",
        category: "masillas",
        subcategory: "masillasG5",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "30cm",
            Ancho:"30cm",
            Profundidad:"3cm",
            Color: "Blanco",
            Peso: "5kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Masilla en pasta, lista para usar. ",
            "Formulada de resinas e insumos de alta calidad para una excelente adherencia, trabajabilidad y textura final. ",
            "Fácil de aplicar, perfecto acabado, excelente adherencia, menor riesgo de fisuras y super llenado.",
            "Este producto es fabricado de acuerdo con la norma ASTM C475/C475M."
        ],
        fichaTecnica: "https://etex.azureedge.net/pi780262/original/789466626/ft-masilla-en-pasta-gyplac-20kg_setiembre-2024.pdf",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },{
        id: "22345466",
        code: "410396",
        name: "MASILLA BALDE ANTIHUMEDAD 15 KG / GYPLAC",
        description: "Pasta para masillar juntas de placas de Gyplac Antihumedad AH en zonas que presentan alta humedad. Da una solución a largo plazo porque no se honguea ni daña con la presencia de humedad. Deja lista la superficie para su acabado final con pintura látex.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masillaah.png",
        category: "masillas",
        subcategory: "masillasG15",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "30cm",
            Ancho:"30cm",
            Profundidad:"15cm",
            Color: "Blanco",
            Peso: "15kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Masilla en pasta, lista para usar. ",
            "Formulada de resinas e insumos de alta calidad para una excelente adherencia, trabajabilidad y textura final. ",
            "Fácil de aplicar, perfecto acabado, excelente adherencia, menor riesgo de fisuras y super llenado.",
            "Este producto es fabricado de acuerdo con la norma ASTM C475/C475M."
        ],
        fichaTecnica: "https://drive.google.com/file/d/1Sxpca1ti2YJt_mWvSRzlvEqXQeRCRKI1/view",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "22345656",
        code: "143114",
        name: "MASILLA EN POLVO SECADO 90 MIN SACO 25 KG / GYPLAC",
        description: "Nuestra Masilla en Polvo Gyplac es el complemento ideal para el tratamiento de juntas de placas de yeso Gyplac. Al agregarle agua se obtiene una pasta o mastick que asegura y garantiza una excelente adherencia y una óptima trabajabilidad. Su tiempo de fraguado es de 120 minutos.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masillapolvo.webp",
        category: "masillas",
        subcategory: "masillasGP25",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "70cm",
            Ancho:"20cm",
            Profundidad:"13cm",
            Color: "Blanco",
            Peso: "25kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Fraguado en solo 90 minutos. ",
            "Asegura una excelente adherencia de la cinta Gyplac a la placa de yeso. ",
            "Excelente trabajabilidad y fácil lijado.",
            "Fácil manejo con las herramientas."
        ],
        fichaTecnica: "https://etex.azureedge.net/pi780262/original/789466626/ft-masilla-en-pasta-gyplac-20kg_setiembre-2024.pdf",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "2656",
        code: "VOL143114",
        name: "MASILLA EN POLVO SECADO 90 MIN JUNTAPRO 25 KG / VOLCAN",
        description: "La Masilla JuntaPro Volcán se encuentra disponible en su formato de polvo elaborado a base de sulfato de yeso y aditivos especiales, especial para el tratamiento de junta invisible de Volcanita, se puede usar además para reparar muros de hormigón, ladrillos y estuco.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masillavolcan2.webp",
        category: "masillas",
        subcategory: "masillasVP25",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "70cm",
            Ancho:"20cm",
            Profundidad:"13cm",
            Color: "Blanco",
            Peso: "25kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Fraguado en solo 90 minutos. ",
            "Asegura una excelente adherencia de la cinta Gyplac a la placa de yeso. ",
            "Excelente trabajabilidad y fácil lijado.",
            "Fácil manejo con las herramientas."
        ],
        fichaTecnica: "https://www.volcanperu.com/documents/ficha-tecnica-del-producto/ficha-tcnica-masilla-juntapro.pdf",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "22345456",
        code: "VOL0018",
        name: "MASILLA CAJA JUNTAPRO 20 KG / VOLCAN",
        description: "La Masilla JuntaPro Volcán se encuentra disponible en su formato de polvo elaborado a base de sulfato de yeso y aditivos especiales, especial para el tratamiento de junta invisible de Volcanita, se puede usar además para reparar muros de hormigón, ladrillos y estuco.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masilla-volcan.jpg",
        category: "materiales",
        subcategory: "masillasV20",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "24cm",
            Ancho:"26cm",
            Dimensiones: "20cm",
            Color: "Blanco",
            Peso: "20kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Masilla en pasta, lista para usar. ",
            "Formulada de resinas e insumos de alta calidad para una excelente adherencia, trabajabilidad y textura final. ",
            "Fácil de aplicar, perfecto acabado, excelente adherencia, menor riesgo de fisuras y super llenado.",
            "Este producto es fabricado de acuerdo con la norma ASTM C475/C475M."
        ],
        fichaTecnica: "https://www.volcanperu.com/documents/ficha-tecnica-del-producto/ficha-tcnica-juntapro-cintas-y-masillas.pdf",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "22345676",
        code: "403109",
        name: "MASILLA CAJA 20 KG / CONSTRUTEK",
        description: "La Masilla JuntaPro Volcán se encuentra disponible en su formato de polvo elaborado a base de sulfato de yeso y aditivos especiales, especial para el tratamiento de junta invisible de Volcanita, se puede usar además para reparar muros de hormigón, ladrillos y estuco.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/masilla/masillaconstru.jpg",
        category: "materiales",
        subcategory: "masillasC20",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Masilla",
            Altura: "24cm",
            Ancho:"26cm",
            Dimensiones: "20cm",
            Color: "Blanco",
            Peso: "20kg",
            Rendimiento:"800 g/m2 de tratamieto de juntas con 3 capas"
        },
        features: [
            "Masilla en pasta, lista para usar. ",
            "Formulada de resinas e insumos de alta calidad para una excelente adherencia, trabajabilidad y textura final. ",
            "Fácil de aplicar, perfecto acabado, excelente adherencia, menor riesgo de fisuras y super llenado.",
            "Este producto es fabricado de acuerdo con la norma ASTM C475/C475M."
        ],
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/masillas_1556299495.jpg",
        tags: ["masilla","placa","cintas"],
        stockDisponible:1000,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
];
