import type { Product } from "@/lib/types";

export const perfilesBaldosasProducts: Product[] = [
    {
        id: "000923",
        code: "PREC428417",
        name: "SUSP TEE PRINCIPAL BLANCO 15/16 X 3.66M - CTK",
        description: "La Suspensión Principal construtek es un componente estructural clave para la instalación de cielos rasos en diversos tipos de espacios residenciales, comerciales e industriales.",
        price: 24.99,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/suspendiones/principales.webp",
        category: "cielo rasos",
        subcategory: "principales",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Aluminio",
            Color: "Blanco",
            Largo: "3.66m",
            Ancho: "15/16\"",
            Espesor: "0.5mm",
            Modelo:"Suspensión Principal",
            Uso: "Cielos rasos",
        },
        features: [
            "Fabricada en aluminio, asegurando durabilidad y resistencia.",
            "Diseño resistente al fuego para seguridad adicional.",
            "Ideal para sistemas de cielo raso en diversas áreas.",
        ],
        fichaTecnica: "https://precor.pe/admin_pmp_precor//public/data/product/download/FT%20Masilla%20y%20cintas%20CONSTRUTEK_compressed.pdf202202101619381.pdf",
        tags: ["suspension", "principal", "cielo rasos"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "000925",
        code: "PREC428418",
        name: "SUSP TEE SECUNDARIA BLANCO 15/16 X 1.22M - CTK",
        description: "Cosntrutek y metaldryll se unen para ofrecerte artículos de calidad superior en cielorrasos suspendidos; y, de esta manera, puedas darle una mejor apariencia a tus techos. La suspensión secundaria, es ideal para fijar los falsos cielos en tu casa y oficina. ¡Y son de fácil instalación con herramientas de uso cotidiano!",
        price: 24.99,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/suspendiones/secundario.webp",
        category: "cielo rasos",
        subcategory: "secundarios",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Aluminio",
            Color: "Blanco",
            Largo: "122cm",
            Ancho: "15/16\"",
            Espesor: "0.5mm",
            Modelo:"Suspensión secundaria",
            Uso: "Cielos rasos",
        },
        features: [
            "Fabricada en aluminio, asegurando durabilidad y resistencia.",
            "Diseño resistente al fuego para seguridad adicional.",
            "Ideal para sistemas de cielo raso en diversas áreas.",
        ],
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/suspensiones_1556316071.jpg",
        tags: ["suspension", "secundario", "cielo rasos"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "000929",
        code: "PREC428419",
        name: "SUSP TEE TERCIARIA BLANCO 15/16 X 0.61M - CTK",
        description: "Cosntrutek y metaldryll se unen para ofrecerte artículos de calidad superior en cielorrasos suspendidos; y, de esta manera, puedas darle una mejor apariencia a tus techos. La suspensión secundaria, es ideal para fijar los falsos cielos en tu casa y oficina. ¡Y son de fácil instalación con herramientas de uso cotidiano!",
        price: 24.99,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/suspendiones/terciaria.webp",
        category: "cielo rasos",
        subcategory: "terciaria",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Aluminio",
            Color: "Blanco",
            Largo: "61cm",
            Ancho: "15/16\"",
            Espesor: "0.5mm",
            Modelo:"Suspensión terciaria",
            Uso: "Cielos rasos",
        },
        features: [
            "Fabricada en aluminio, asegurando durabilidad y resistencia.",
            "Diseño resistente al fuego para seguridad adicional.",
            "Ideal para sistemas de cielo raso en diversas áreas.",
        ],
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/suspensiones_1556316071.jpg",
        tags: ["suspension", "terciaria", "cielo rasos"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "000943",
        code: "PREC428420",
        name: "ANGULO DE SUSP. PERIMETRAL BLANCO 15/16 X 3M - CTK",
        description: "El Ángulo Perimetral 19.5x22x3050 mm de construtek es el aliado perfecto para tus proyectos de construcción y cielo raso. Fabricado en aluminio de alta calidad, es esencial para crear estructuras resistentes y seguras, optimizando cada rincón de tu espacio residencial, comercial o industrial. ",
        price: 24.99,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/suspendiones/angulo.webp",
        category: "cielo rasos",
        subcategory: "angulo",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Aluminio",
            Color: "Blanco",
            Largo: "3 m",
            Ancho: "15/16\"",
            Espesor: "0.5mm",
            Modelo:"Suspensión perimetral",
            Uso: "Cielos rasos",
        },
        features: [
            "Fabricada en aluminio, asegurando durabilidad y resistencia.",
            "Diseño resistente al fuego para seguridad adicional.",
            "Ideal para sistemas de cielo raso en diversas áreas.",
        ],
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/suspensiones_1556316071.jpg",
        tags: ["suspension", "angulo","perimetral", "cielo rasos"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "000456",
        code: "ALAM001",
        name: "ALAMBRE GALVANIZADO #16 - KILO",
        description: "l Alambre galvanizado 16 x 1 kg  es la opción perfecta para quienes buscan un material versátil y de alta calidad. Fabricado con bajo contenido de carbono y un acabado galvanizado simple, es fácil de manipular y ofrece una excelente resistencia a la corrosión, lo que lo convierte en ideal para aplicaciones industriales, agrícolas y de construcción.",
        price: 24.99,
        discount: 5,
        rating: 4.5,
        reviews: 30,
        image: "/suspendiones/alambre.jpg",
        category: "cielo rasos",
        subcategory: "alambre",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Material: "Aluminio",
            Color: "Plata",
            Tipo: "Galvanizado",
            Peso: "1kg",
            Modelo:"#16",
            Uso: "Cielos rasos ,Aplicaciones. Industrial: Gaviones, cables, entre otros. Agrícola: Cercos lisos, huertos, entre otros. Construcción: Amarre de Varillas, construcción civil, encofrados, cubiertas, cercas, armado de techo.",
        },
        features: [
            "Galvanizado simple que asegura alta resistencia a la corrosión.",
            "Bajo contenido de carbono para una manipulación fácil y eficiente.",
            "Ideal para aplicaciones industriales, agrícolas y de construcción.",
            "Fácil de cortar y manipular con herramientas adecuadas.",   
        ],
        fichaTecnica: "",
        tags: ["suspension", "angulo","perimetral", "cielo rasos","alambre"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
];
