import type { Product } from "@/lib/types";

export const perfilesProducts: Product[] = [
    {
        id: "1",
        code: "403036",
        name: "PARANTE DE 64 X 38 X 0.45 X 3.00M / CONSTRUTEK",
        description: "Para el armado de estructuras para paredes y cielos rasos",
        price: 0,
        discount: 0,
        rating: 4.3,
        reviews: 12,
        image: "/perfiles/parante64.webp",
        category: "drywall",
        subcategory: "Parante",
        isNew: false,
        inStock: true,
        stockDisponible: 100,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["parante", "perfil", "drywall", "64x38", "0.45mm"],
        technicalSpecs: {
            Ancho: "64mm",
            Alto: "38mm",
            Espesor: "0.45mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Estructura para muros y cielos rasos"
        },
        features: [
            "Perfil galvanizado de alta resistencia",
            "Fácil de instalar y cortar",
            "Ideal para sistemas Drywall"
        ]
    },
    {
        id: "2",
        code: "403042",
        name: "PARANTE DE 89 X 38 X 0.45 X 3.00M / CONSTRUTEK",
        description: "Para el armado de estructuras para paredes y cielos rasos",
        price: 0,
        discount: 0,
        rating: 4.3,
        reviews: 11,
        image: "/perfiles/parante89.jpg",
        category: "drywall",
        subcategory: "Parante",
        isNew: false,
        inStock: true,
        stockDisponible: 90,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["parante", "perfil", "drywall", "89x38", "0.45mm"],
        technicalSpecs: {
            Ancho: "89mm",
            Alto: "38mm",
            Espesor: "0.45mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Estructura para muros y cielos rasos"
        },
        features: [
            "Alta resistencia estructural",
            "Perfil galvanizado para ambientes secos",
            "Compatible con sistemas Drywall"
        ]
    },
    {
        id: "3",
        code: "403031",
        name: "PARANTE DE 38 X 38 X 0.45 X 3.00M / CONSTRUTEK",
        description: "Para el armado de estructuras para paredes y cielos rasos",
        price: 0,
        discount: 0,
        rating: 4.2,
        reviews: 10,
        image: "/perfiles/parante38.jpg",
        category: "drywall",
        subcategory: "Parante",
        isNew: false,
        inStock: true,
        stockDisponible: 80,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["parante", "perfil", "drywall", "38x38", "0.45mm"],
        technicalSpecs: {
            Ancho: "38mm",
            Alto: "38mm",
            Espesor: "0.45mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Estructura para muros y cielos rasos"
        },
        features: [
            "Fácil de transportar e instalar",
            "Uso eficiente en espacios reducidos",
            "Resistencia en sistemas livianos"
        ]
    },
    {
        id: "4",
        code: "403084",
        name: "OMEGA DE 30 X 24 X 15 X 0.45 X 3.00M / CONSTRUCTECK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para vigas o correas de techos, sistema de cielo raso y soporte de conexiones internas.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 13,
        image: "/perfiles/omega.jpg",
        category: "drywall",
        subcategory: "omega",
        isNew: false,
        inStock: true,
        stockDisponible: 75,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["omega", "perfil", "drywall", "estructura", "0.45mm"],
        technicalSpecs: {
            Ancho: "30mm",
            Alto: "24mm",
            Espesor: "0.45mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Cielos rasos y soporte interno"
        },
        features: [
            "Diseño tipo omega para rigidez estructural",
            "Ideal para techos y soportes",
            "Galvanizado anticorrosivo"
        ]
    },
    {
        id: "5",
        code: "403081",
        name: "ESQUINERO DE  30 X 30 X 0.30 X 3.00M / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.1,
        reviews: 9,
        image: "/perfiles/esquinero.jpg",
        category: "drywall",
        subcategory: "esquinero",
        isNew: false,
        inStock: true,
        stockDisponible: 120,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["esquinero", "perfil", "drywall", "38x30", "0.45mm"],
        technicalSpecs: {
            Ancho: "30mm",
            Alto: "30mm",
            Espesor: "0.30mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Para uso de proteccion de zonas expuestas ,como esquinas y filos de tabiquerias en construcciones en drywall."
        },
        features: [
            "Colocar los esquineros para mejorar la resistencia en zonas vulnerables de una edificación",
            "No colocar esquineros doblados",
            "Usar los tornillos adecuados para su fijación"
        ]
    },
    {
        id: "6",
        code: "ETEX4049833",
        name: "ESQUINERO PLASTICO VINIL RÍGIDO 30 X 30 X 3.00M",
        description: "Esquinero de PVC para sistemas Drywall",
        price: 0,
        discount: 0,
        rating: 4.2,
        reviews: 10,
        image: "/perfiles/esquineroplastico.jpg",
        category: "drywall",
        subcategory: "esquinero",
        isNew: false,
        inStock: true,
        stockDisponible: 110,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "",
        tags: ["esquinero", "plastico", "drywall", "pvc", "3m"],
        technicalSpecs: {
            Ancho: "30mm",
            Alto: "30mm",
            Espesor: "0.30mm",
            Largo: "3.00m",
            Material: "PVC",
            Uso: "Para uso de proteccion de zonas expuestas ,como esquinas y filos de tabiquerias en construcciones en drywall."
        },
        features: [
            "Colocar los esquineros para mejorar la resistencia en zonas vulnerables de una edificación",
            "No colocar esquineros doblados",
            "Usar los tornillos adecuados para su fijación"
        ]
    },
    {
        id: "7",
        code: "ETEX4049832",
        name: "ESQUINERO PLASTICO VINIL CURVO 30 X 30 X 3.00M",
        description: "Esquinero de PVC para sistemas Drywall",
        price: 0,
        discount: 0,
        rating: 4.2,
        reviews: 10,
        image: "/perfiles/esquinerocuvo.png",
        category: "drywall",
        subcategory: "esquinero",
        isNew: false,
        inStock: true,
        stockDisponible: 110,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "",
        tags: ["esquinero", "plastico", "drywall", "pvc", "3m"],
        technicalSpecs: {
            Ancho: "30mm",
            Alto: "30mm",
            Espesor: "0.30mm",
            Largo: "3.00m",
            Material: "PVC",
            Uso: "Para uso de proteccion de zonas expuestas ,como esquinas y filos de tabiquerias en construcciones en drywall."
        },
        features: [
            "Colocar los esquineros para mejorar la resistencia en zonas vulnerables de una edificación",
            "No colocar esquineros doblados",
            "Usar los tornillos adecuados para su fijación"
        ]
    },
    {
        id: "8",
        code: "402987",
        name: "RIEL DE 39 X 25 X 0.45 X 3.00M GAL / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.2,
        reviews: 8,
        image: "/perfiles/riel39.jpg",
        category: "drywall",
        subcategory: "riel",
        isNew: false,
        inStock: true,
        stockDisponible: 85,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["riel", "perfil", "drywall", "35x22", "0.45mm"],
        technicalSpecs: {
            Ancho: "39mm",
            Alto: "25mm",
            Espesor: "0.45mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Uso en la construcción de divisiones, revoque de paredes curvas y detalles decorativos."
        },
        features: [
            "Alta resistencia contra la corrosión.",
            "Estructura liviana.",
            "Fácil y rápido de instalar. Diseño flexible.",
            "Es material desmontable. Es incombustible."
        ]
    },
    {
        id: "9",
        code: "402991",
        name: "RIEL DE 65 X 25 X 0.45 X 3.00M GAL / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.3,
        reviews: 7,
        image: "/perfiles/riel65.jpg",
        category: "drywall",
        subcategory: "riel",
        isNew: false,
        inStock: true,
        stockDisponible: 95,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["riel", "perfil", "drywall", "65", "0.45mm"],
        technicalSpecs: {
            Ancho: "65mm",
            Alto: "25mm",
            Espesor: "0.45mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Protección de bordes exteriores"
        },
        features: [
            "Alta resistencia contra la corrosión.",
            "Estructura liviana.",
            "Fácil y rápido de instalar. Diseño flexible.",
            "Es material desmontable. Es incombustible."
        ]
    },
    {
        id: "10",
        code: "402995",
        name: "RIEL DE 90 X 25 X 0.45 X 3.00M GAL / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.1,
        reviews: 6,
        image: "/perfiles/riel90.jpg",
        category: "drywall",
        subcategory: "riel",
        isNew: false,
        inStock: true,
        stockDisponible: 90,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["ángulo", "perfil", "drywall", "refuerzo", "0.35mm"],
        technicalSpecs: {
            Ancho: "90mm",
            Alto: "25mm",
            Espesor: "0.45mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Refuerzo de estructuras Drywall"
        },
        features: [
            "Alta resistencia a la corrosión.",
            "Fácil y rápido de instalar.",
            "Diseño flexible para múltiples usos.",
            "Ideal para construir muros, vigas, cielo raso, entre otros."
        ]
    }, {
        id: "11",
        code: "403040",
        name: "PARANTE DE  64 X 38 X 0.90 X 3.00M / CONSTRUTEK",
        description: "El Parante de Acero Galvanizado Metalcon 64x0.9mmx3.00m es la solución ideal para tus proyectos de construcción en seco. Con alta resistencia a la corrosión y diseño flexible, este parante es fácil y rápido de instalar. ",
        price: 0,
        discount: 0,
        rating: 4.4,
        reviews: 12,
        image: "/perfiles/parante64pesado.jpg",
        category: "drywall",
        subcategory: "Parante",
        isNew: false,
        inStock: true,
        stockDisponible: 100,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["parante", "perfil", "drywall", "64x38", "0.45mm"],
        technicalSpecs: {
            Ancho: "64mm",
            Alto: "38mm",
            Espesor: "0.45mm",
            Largo: "2.60m",
            Material: "Galvanizado",
            Uso: "Elemento vertical para estructuras Drywall"
        },
        features: [
            "Alta resistencia a la corrosión.",
            "Fácil y rápido de instalar.",
            "Diseño flexible para múltiples usos.",
            "Ideal para construir muros, vigas, cielo raso, entre otros."
        ]
    },
    {
        id: "12",
        code: "403047",
        name: "PARANTE DE  89 X 38 X 0.90 X 3.00M / CONSTRUTEK",
        description: "El Parante de Acero Galvanizado Metalcon 64x0.9mmx3.00m es la solución ideal para tus proyectos de construcción en seco. Con alta resistencia a la corrosión y diseño flexible, este parante es fácil y rápido de instalar. ",
        price: 0,
        discount: 0,
        rating: 4.4,
        reviews: 14,
        image: "/perfiles/parante64pesado.jpg",
        category: "drywall",
        subcategory: "Parante",
        isNew: false,
        inStock: true,
        stockDisponible: 100,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["parante", "perfil", "drywall", "64x38", "3.00m"],
        technicalSpecs: {
            Ancho: "89mm",
            Alto: "38mm",
            Espesor: "0.90mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Elemento vertical para estructuras Drywall"
        },
        features: [
            "Alta resistencia a la corrosión.",
            "Fácil y rápido de instalar.",
            "Diseño flexible para múltiples usos.",
            "Ideal para construir muros, vigas, cielo raso, entre otros."
        ]
    },
    {
        id: "13",
        code: "40304756",
        name: "PARANTE DE  38 X 38 X 0.90 X 3.00M / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 10,
        image: "/perfiles/parante38.jpg",
        category: "drywall",
        subcategory: "Parante",
        isNew: false,
        inStock: true,
        stockDisponible: 100,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["parante", "perfil", "drywall", "89x38", "2.60m"],
        technicalSpecs: {
            Ancho: "38mm",
            Alto: "38mm",
            Espesor: "0.45mm",
            Largo: "3.0m",
            Material: "Galvanizado",
            Uso: "Soporte vertical para estructuras Drywall"
        },
        features: [
            "Alta resistencia a la corrosión.",
            "Fácil y rápido de instalar.",
            "Diseño flexible para múltiples usos.",
            "Ideal para construir muros, vigas, cielo raso, entre otros."
        ]
    },
    {
        id: "14",
        code: "40303854",
        name: "RIEL DE 65 X 38X 0.90 X 3.00M / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 11,
        image: "/perfiles/riel65.jpg",
        category: "drywall",
        subcategory: "riel",
        isNew: false,
        inStock: true,
        stockDisponible: 90,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["riel", "perfil", "drywall", "pesado", "3.00m"],
        technicalSpecs: {
            Ancho: "65mm",
            Alto: "38mm",
            Espesor: "0.90mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Sirve como guía de parante."
        },
        features: [
            "Alta resistencia a la corrosión.",
            "Fácil y rápido de instalar.",
            "Diseño flexible para múltiples usos.",
            "Ideal para construir muros, vigas, cielo raso, entre otros."
        ]
    },
    {
        id: "15",
        code: "402993",
        name: "RIEL DE 90 X 38X 0.90 X 3.00M / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.3,
        reviews: 9,
        image: "/perfiles/riel65.jpg",
        category: "drywall",
        subcategory: "riel",
        isNew: false,
        inStock: true,
        stockDisponible: 80,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["omega", "perfil", "drywall", "suspensión", "0.45mm"],
        technicalSpecs: {
            Ancho: "90mm",
            Alto: "10mm",
            Espesor: "0.90mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Sirve como guía de parante."
        },
        features: [
            "Alta resistencia a la corrosión.",
            "Fácil y rápido de instalar.",
            "Diseño flexible para múltiples usos.",
            "Ideal para construir muros, vigas, cielo raso, entre otros."
        ]
    },
    {
        id: "16",
        code: "40299339",
        name: "RIEL DE 39 X 38X 0.90 X 3.00M / CONSTRUTEK",
        description: "Perfil Drywall galvanizado para construcción en seco. Son utilizados para proteccion de golpes en esquinas de muros, ventanas, puertas, y bordes en general.",
        price: 0,
        discount: 0,
        rating: 4.3,
        reviews: 10,
        image: "/perfiles/riel39.jpg",
        category: "drywall",
        subcategory: "riel",
        isNew: false,
        inStock: true,
        stockDisponible: 85,
        ubicacionAlmacen: "Almacén Central",
        date: "2024-05-01",
        fichaTecnica: "https://precor.pe/admin_pmp_precor/public/data/product/download/perfiles-drywall_15542448042.pdf",
        tags: ["riel", "perfil", "drywall", "cielo raso", "0.90mm"],
        technicalSpecs: {
            Ancho: "39mm",
            Alto: "38mm",
            Espesor: "0.90mm",
            Largo: "3.00m",
            Material: "Galvanizado",
            Uso: "Sirve como guía de parante."
        },
        features: [
            "Alta resistencia a la corrosión.",
            "Fácil y rápido de instalar.",
            "Diseño flexible para múltiples usos.",
            "Ideal para construir muros, vigas, cielo raso, entre otros."
        ]
    }
];
