import type { Product } from "@/lib/types";

export const superboardProducts: Product[] = [
    {
        id: "2876866",
        code: "113106",
        name: "Placa Fibrocemento Multiplaca 4 mm 1.22x2.44 metros Mutiplaca",
        description: "La Placa Fibrocemento Multiplaca 4 mm 1.22x2.44 metros Mutiplaca es la solución perfecta para quienes buscan materiales duraderos y de alta calidad para la construcción.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/catalago/multiplaca-4mm.jpg",
        category: "superboard",
        subcategory: "superboard",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "4mm",
            Peso: "17.1kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Interiores y exteriores",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar."
        ],
        fichaTecnica: "https://etex.azureedge.net/pi809214/original/242601842/ficha-tecnica-multiplaca-4-mm",
        tags: ["placa", "multiplaca", "fibrocemento"],
        stockDisponible: 110,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "28768366",
        code: "113269",
        name: "Placa Fibrocemento Superboard 6 mm 1.22x2.44 metros ",
        description: "Placa Fibrocemento Superboard ST 6mm 1.22x2.44 metros es una excelente opción para proyectos de construcción que requieran materiales resistentes y de alta durabilidad.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/catalago/plancha6mm.webp",
        category: "superboard",
        subcategory: "superboard",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "6mm",
            Peso: "25.6kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Interiores y exteriores",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar."
        ],
        fichaTecnica: "https://etex.azureedge.net/pi789328/original/368957766/cielo-raso-6mm-1.pdf",
        tags: ["placa", "6 mm", "fibrocemento"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "28768366",
        code: "113065",
        name: "Placa Fibrocemento Superboard 8 mm 1.22x2.44 metros",
        description: "La Placa Fibrocemento Superboard ST 8mm 1.22x2.44 metros es la solución ideal para una amplia variedad de aplicaciones constructivas.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/catalago/plancha8mm.jpg",
        category: "superboard",
        subcategory: "superboard",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "8mm",
            Peso: "34.2kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Interiores y exteriores",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar."
        ],
        fichaTecnica: "https://etex.azureedge.net/pi789332/original/-1775983220/ficha-tecnica-pared-interior-8-mm",
        tags: ["placa", "8 mm", "fibrocemento"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "287683600",
        code: "113066",
        name: "Placa Fibrocemento Superboard 10 mm 1.22x2.44 metros",
        description: "La Placa Fibrocemento Superboard ST 10mm 1.22x2.44 metros es la solución ideal para una amplia variedad de aplicaciones constructivas.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/catalago/plancha10mm.webp",
        category: "superboard",
        subcategory: "superboard",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "10mm",
            Peso: "43.7kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Exteriores - Fachadas",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar.",
            "Resistente al Impacto"
        ],
        fichaTecnica: "https://etex.azureedge.net/pi789326/original/-909841951/ficha-tecnica-fachada-10-mm",
        tags: ["placa", "10 mm", "fibrocemento"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "28683600",
        code: "142698",
        name: "PLANCHA SUPERBOARD TEXTURADA MADERA 1.20 X 2.44 X 6.00MM",
        description: "Superboard Texturado es una placa de cemento con textura madera que brinda calidez y destaca la estética decorativa, permitiendo generar un aspecto modulado.",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/catalago/planchatexturada.webp",
        category: "superboard Texturada",
        subcategory: "superboardt",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "6mm",
            Peso: "24.5kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Interiores y exteriores",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar.",
            "Resistente al Impacto"
        ],
        fichaTecnica: "",
        tags: ["placa", "madera", "texturada", "fibrocemento"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "287683600",
        code: "113089",
        name: "Placa Fibrocemento Superboard 15 mm 1.22x2.44 metros",
        description: "Superboard Entrepiso 15 mm es una placa plana de fibrocemento fabricada mediante un proceso de autoclave (alta presión, temperatura y humedad).",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/catalago/plancha15mm.jpg",
        category: "superboard",
        subcategory: "superboard",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "15mm",
            Peso: "64.8kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Exteriores - Fachadas",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar.",
            "Resistente al Impacto"
        ],
        fichaTecnica: "https://etex.azureedge.net/pi789323/original/289557077/entrepiso-15mm.pdf",
        tags: ["placa", "15 mm", "fibrocemento", "entrepiso"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "2876836003",
        code: "113090",
        name: "SUPERBOARD ENTREPISO PLUS 1.20 X 2.44 17 mm ",
        description: "Superboard Entrepiso Plus 17 mm es una placa plana de fibrocemento fabricada mediante un proceso de autoclave (alta presión, temperatura y humedad)..",
        price: 0,
        discount: 0,
        rating: 4.5,
        reviews: 30,
        image: "/catalago/plancha17mm.jpg",
        category: "superboard",
        subcategory: "superboard",
        isNew: false,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "17mm",
            Peso: "70.8kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Entrepisos Plus",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar.",
            "Resistente al Impacto"
        ],
        fichaTecnica: "https://etex.azureedge.net/pi789324/original/1204608410/entrepiso-17mm.pdf",
        tags: ["placa", "17 mm", "fibrocemento", "entrepiso"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
    {
        id: "28768360233",
        code: "11309124",
        name: "SUPERBOARD ENTREPISO PLUS 1.20 X 2.44 20 mm ",
        description: "Superboard Entrepiso Extra Plus 20 mm es una placa plana de fibrocemento fabricada mediante un proceso de autoclave (alta presión, temperatura y humedad).",
        price: 0,
        discount: 0,
        rating: 5,
        reviews: 130,
        image: "/catalago/plancha20mm.jpg",
        category: "superboard",
        subcategory: "superboard",
        isNew: true,
        inStock: true,
        date: "2024-01-10",
        technicalSpecs: {
            Alto: "2.44m",
            Ancho: "1.22m",
            Espesor: "20mm",
            Peso: "85.8kg",
            Color: "Gris",
            Material: "Fibrocemento",
            Rendimiento: "2.97m2",
            Uso: "Entrepisos Extra Plus",
        },
        features: [
            "Composición robusta con alta estabilidad dimensional y durabilidad.",
            "Resistente a la humedad, ideal para aplicaciones exteriores e interiores",
            "Resistente a termitas y roedores, asegurando una vida útil prolongada.",
            "Fácil de cortar, transportar e instalar.",
            "Resistente al Impacto"
        ],
        fichaTecnica: "https://etex.azureedge.net/pi789330/original/1678957493/ficha-tecnica-entrepiso-20-mm",
        tags: ["placa", "20 mm", "fibrocemento", "entrepiso"],
        stockDisponible: 100,
        ubicacionAlmacen: "nuevo chimbote - chimbote",
    },
];
