import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    code: "TP-2050-PRO",
    name: "Taladro Percutor Profesional 20V",
    description:
      "Taladro percutor inalámbrico de alta potencia con batería de litio de 20V, incluye 2 baterías y maletín. Ideal para trabajos profesionales en construcción y carpintería. Diseño ergonómico para reducir la fatiga durante uso prolongado.",
    price: 149.99,
    discount: 10,
    rating: 4.8,
    reviews: 124,
    image: "/placeholder.svg?height=400&width=400",
    category: "herramientas-electricas",
    subcategory: "taladros",
    isNew: true,
    inStock: true,
    date: "2023-11-15",
    technicalSpecs: {
      Potencia: "20V",
      Velocidad: "0-1800 RPM",
      "Torque máximo": "60 Nm",
      "Capacidad del mandril": "13mm",
      Peso: "1.8 kg",
      Incluye: "2 baterías, cargador, maletín",
      Garantía: "3 años",
    },
    features: [
      "Motor sin escobillas para mayor durabilidad",
      "Luz LED integrada para trabajar en áreas oscuras",
      "21 posiciones de embrague para control preciso",
      "Batería de litio de carga rápida",
      "Mango ergonómico con agarre suave",
    ],
  },
  {
    id: "2",
    code: "DP-42-PRE",
    name: "Juego de Destornilladores de Precisión 42 piezas",
    description:
      "Set completo de destornilladores de precisión con puntas intercambiables para electrónica y reparaciones. Fabricado con acero S2 de alta calidad para mayor durabilidad y resistencia a la torsión. Estuche organizador con compartimentos etiquetados.",
    price: 29.99,
    discount: 0,
    rating: 4.5,
    reviews: 89,
    image: "/placeholder.svg?height=400&width=400",
    category: "herramientas-manuales",
    subcategory: "destornilladores",
    isNew: false,
    inStock: true,
    date: "2023-10-05",
    technicalSpecs: {
      Material: "Acero S2",
      "Cantidad de piezas": "42",
      "Tipos de puntas": "Phillips, Torx, Hex, Planas, Triangulares",
      Mango: "Antideslizante con rotación libre",
      Estuche: "Aluminio con interior organizado",
      Peso: "0.5 kg",
      Garantía: "1 año",
    },
    features: [
      "Puntas magnéticas para fácil manipulación de tornillos",
      "Mango ergonómico con zona de agarre suave",
      "Estuche de aluminio resistente a impactos",
      "Incluye extensión flexible para lugares de difícil acceso",
      "Ideal para reparación de electrónicos, relojes y gafas",
    ],
  },
  {
    id: "3",
    code: "SC-1800-LAS",
    name: "Sierra Circular 1800W con Guía Láser",
    description:
      "Sierra circular potente con guía láser, ajuste de profundidad y ángulo, incluye 3 discos para diferentes materiales. Sistema de aspiración integrado para mantener la línea de corte limpia. Motor de alto rendimiento para cortes precisos en madera, plástico y aluminio.",
    price: 189.99,
    discount: 15,
    rating: 4.7,
    reviews: 56,
    image: "/placeholder.svg?height=400&width=400",
    category: "herramientas-electricas",
    subcategory: "sierras",
    isNew: false,
    inStock: true,
    date: "2023-09-20",
    technicalSpecs: {
      Potencia: "1800W",
      Velocidad: "5200 RPM",
      "Diámetro de disco": "185mm",
      "Profundidad máxima de corte": "63mm a 90°, 45mm a 45°",
      "Ángulo de bisel": "0-45°",
      Peso: "4.2 kg",
      Garantía: "2 años",
    },
    features: [
      "Guía láser para cortes precisos",
      "3 discos incluidos: madera, plástico y aluminio",
      "Sistema de aspiración integrado",
      "Protector retráctil de seguridad",
      "Base de aluminio ajustable",
    ],
  },
  {
    id: "4",
    code: "CM-8M-PRO",
    name: "Cinta Métrica Profesional 8m",
    description:
      "Cinta métrica retráctil con bloqueo automático, carcasa resistente a impactos y gancho magnético. Escala dual en métrico e imperial con marcas claras y precisas. Diseño ergonómico con revestimiento de goma para mejor agarre.",
    price: 12.99,
    discount: 0,
    rating: 4.3,
    reviews: 210,
    image: "/placeholder.svg?height=400&width=400",
    category: "medicion-nivelacion",
    subcategory: "cintas-metricas",
    isNew: false,
    inStock: true,
    date: "2023-08-12",
    technicalSpecs: {
      Longitud: "8 metros / 26 pies",
      "Ancho de cinta": "25mm",
      "Material de carcasa": "ABS con revestimiento de goma",
      Gancho: "Magnético con remaches reforzados",
      Escala: "Métrica e imperial",
      Precisión: "Clase II",
      Garantía: "Lifetime",
    },
    features: [
      "Bloqueo automático para mediciones precisas",
      "Gancho magnético para trabajar sin asistencia",
      "Cinta recubierta de nylon para mayor durabilidad",
      "Carcasa ergonómica resistente a caídas",
      "Clip para cinturón integrado",
    ],
  },
  {
    id: "5",
    code: "LC-12-CRV",
    name: "Juego de Llaves Combinadas 12 piezas",
    description:
      "Set de llaves combinadas en acero al cromo vanadio, acabado cromado y tamaños de 8mm a 19mm. Diseño de perfil delgado para acceder a espacios reducidos. Organizado en estuche enrollable para fácil transporte y almacenamiento.",
    price: 45.99,
    discount: 5,
    rating: 4.6,
    reviews: 78,
    image: "/placeholder.svg?height=400&width=400",
    category: "herramientas-manuales",
    subcategory: "llaves",
    isNew: false,
    inStock: true,
    date: "2023-07-30",
    technicalSpecs: {
      Material: "Acero al cromo vanadio",
      Acabado: "Cromado pulido",
      Tamaños: "8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19mm",
      "Ángulo de cabeza": "15°",
      Estuche: "Lona enrollable con compartimentos",
      "Peso total": "1.2 kg",
      Garantía: "Lifetime",
    },
    features: [
      "Perfil delgado para espacios reducidos",
      "Cabeza pulida para evitar daños en tuercas",
      "Diseño de agarre seguro para mayor torque",
      "Resistentes a la corrosión y desgaste",
      "Marcas de tamaño grabadas con láser",
    ],
  },
  {
    id: "6",
    code: "NL-360-AUTO",
    name: "Nivel Láser Autonivelante 360°",
    description:
      "Nivel láser de líneas cruzadas con autonivelación, base giratoria y trípode incluido. Proyecta líneas horizontales y verticales de 360° para nivelación completa de habitaciones. Incluye detector para uso en exteriores y gafas para mejorar la visibilidad del láser.",
    price: 79.99,
    discount: 0,
    rating: 4.9,
    reviews: 42,
    image: "/placeholder.svg?height=400&width=400",
    category: "medicion-nivelacion",
    subcategory: "niveles",
    isNew: true,
    inStock: true,
    date: "2023-12-01",
    technicalSpecs: {
      "Tipo de láser": "Clase 2, 635nm",
      Precisión: "±2mm a 10m",
      "Rango de autonivelación": "±4°",
      Alcance: "20m (50m con detector)",
      Alimentación: "3 pilas AA o batería recargable",
      Autonomía: "8 horas continuas",
      Protección: "IP54 (polvo y salpicaduras)",
      Garantía: "2 años",
    },
    features: [
      "Líneas láser 360° horizontales y verticales",
      "Autonivelación con alerta de desnivel",
      "Base giratoria con graduación fina",
      "Modo de bloqueo para líneas inclinadas",
      "Trípode ajustable incluido",
      "Estuche de transporte resistente a impactos",
    ],
  },
  {
    id: "7",
    code: "MC-PRO-16",
    name: "Martillo de Carpintero Profesional",
    description:
      "Martillo de carpintero con mango ergonómico antideslizante y cabeza de acero forjado. Diseñado para máxima absorción de impactos y mínima fatiga. Uña curvada para extracción eficiente de clavos y balance perfecto para mayor precisión.",
    price: 24.99,
    discount: 0,
    rating: 4.4,
    reviews: 156,
    image: "/placeholder.svg?height=400&width=400",
    category: "herramientas-manuales",
    subcategory: "martillos",
    isNew: false,
    inStock: true,
    date: "2023-06-15",
    technicalSpecs: {
      "Peso de cabeza": "16 oz (450g)",
      "Material de cabeza": "Acero forjado de alta carbono",
      Mango: "Fibra de vidrio con revestimiento de goma",
      "Longitud total": "33 cm",
      Cara: "Ligeramente convexa, pulida",
      Uña: "Curvada con ranura para extracción de clavos",
      Garantía: "Lifetime",
    },
    features: [
      "Absorción de vibraciones para reducir fatiga",
      "Balance perfecto para mayor precisión",
      "Mango ergonómico con agarre seguro",
      "Uña optimizada para extracción de clavos",
      "Resistente a temperaturas extremas",
    ],
  },
  {
    id: "8",
    code: "LO-300-CDP",
    name: "Lijadora Orbital 300W con Colector de Polvo",
    description:
      "Lijadora orbital con sistema de aspiración, 6 velocidades y base de velcro para cambio rápido de lijas. Sistema de control de vibración para mayor comodidad en uso prolongado. Diseño compacto para acceder a espacios reducidos.",
    price: 69.99,
    discount: 10,
    rating: 4.2,
    reviews: 63,
    image: "/placeholder.svg?height=400&width=400",
    category: "herramientas-electricas",
    subcategory: "lijadoras",
    isNew: false,
    inStock: true,
    date: "2023-05-22",
    technicalSpecs: {
      Potencia: "300W",
      Velocidad: "6000-12000 OPM",
      "Tamaño de base": "115 x 230mm",
      Órbita: "2mm",
      "Sistema de aspiración": "Integrado con bolsa",
      "Nivel de ruido": "82 dB",
      Peso: "2.1 kg",
      Garantía: "2 años",
    },
    features: [
      "Control electrónico de velocidad",
      "Sistema de aspiración eficiente",
      "Cambio rápido de papel de lija con velcro",
      "Empuñadura ergonómica con superficie soft-grip",
      "Incluye 10 hojas de lija de diferentes granos",
    ],
  },
  {
    id: "9",
    code: "BP-PRO-5",
    name: "Set de Brochas Profesionales 5 piezas",
    description:
      "Juego de brochas de alta calidad con cerdas sintéticas y mangos ergonómicos para pinturas y barnices. Diseñadas para aplicación uniforme sin marcas de brocha. Fáciles de limpiar y resistentes a disolventes.",
    price: 34.99,
    discount: 0,
    rating: 4.7,
    reviews: 91,
    image: "/placeholder.svg?height=400&width=400",
    category: "pinturas-acabados",
    subcategory: "brochas-rodillos",
    isNew: false,
    inStock: true,
    date: "2023-04-10",
    technicalSpecs: {
      Tamaños: '1/2", 1", 1.5", 2", 3"',
      "Material de cerdas": "Filamentos sintéticos de alta densidad",
      Mangos: "Madera tratada con agarre ergonómico",
      Férula: "Acero inoxidable",
      Compatibilidad: "Pinturas al agua, esmaltes y barnices",
      Garantía: "1 año",
    },
    features: [
      "Cerdas de alta densidad para acabado uniforme",
      "No dejan marcas ni sueltan pelos",
      "Mangos ergonómicos para mayor control",
      "Fáciles de limpiar con agua y jabón",
      "Estuche de almacenamiento incluido",
    ],
  },
  {
    id: "10",
    code: "CS-VIS-PRO",
    name: "Casco de Seguridad con Visor Integrado",
    description:
      "Casco de seguridad con visor retráctil, ajuste de tamaño y protección contra impactos. Certificado según normas internacionales de seguridad. Diseño ventilado para mayor comodidad en trabajos prolongados.",
    price: 29.99,
    discount: 5,
    rating: 4.8,
    reviews: 47,
    image: "/placeholder.svg?height=400&width=400",
    category: "seguridad",
    subcategory: "cascos",
    isNew: true,
    inStock: true,
    date: "2023-11-28",
    technicalSpecs: {
      Material: "ABS de alta resistencia",
      Certificaciones: "EN 397, ANSI Z89.1",
      Visor: "Policarbonato anti-rayones y anti-empañamiento",
      Ajuste: "Sistema de rueda con 8 posiciones",
      Peso: "450g",
      "Temperatura de uso": "-30°C a +50°C",
      Garantía: "2 años",
    },
    features: [
      "Visor retráctil con protección UV",
      "Sistema de ventilación ajustable",
      "Banda para sudor reemplazable",
      "Compatible con protectores auditivos",
      "Reflectores de alta visibilidad",
    ],
  },
  {
    id: "11",
    code: "AA-850-KIT",
    name: "Amoladora Angular 850W con Kit de Discos",
    description:
      "Amoladora angular potente con protección contra sobrecalentamiento, incluye 5 discos para diferentes materiales. Sistema anti-vibración para mayor comodidad y precisión. Protector ajustable sin herramientas.",
    price: 89.99,
    discount: 0,
    rating: 4.6,
    reviews: 73,
    image: "/placeholder.svg?height=400&width=400",
    category: "herramientas-electricas",
    subcategory: "amoladoras",
    isNew: false,
    inStock: true,
    date: "2023-10-18",
    technicalSpecs: {
      Potencia: "850W",
      Velocidad: "11000 RPM",
      "Diámetro de disco": '115mm (4.5")',
      Eje: "M14",
      Empuñadura: "Lateral anti-vibración, 3 posiciones",
      Protección: "Reinicio cero, protector ajustable",
      Peso: "2.3 kg",
      Garantía: "3 años",
    },
    features: [
      "Motor protegido contra polvo y escombros",
      "Sistema de arranque suave",
      "Cambio rápido de disco sin herramientas",
      "5 discos incluidos: corte metal, piedra, cerámica, desbaste y diamante",
      "Maletín de transporte resistente",
    ],
  },
  {
    id: "12",
    code: "LR-TAC-USB",
    name: "Linterna LED Recargable de Alta Potencia",
    description:
      "Linterna LED táctica con zoom, 5 modos de iluminación y batería recargable por USB. Cuerpo de aluminio aeronáutico resistente a impactos y condiciones climáticas extremas. Ideal para actividades al aire libre y emergencias.",
    price: 39.99,
    discount: 15,
    rating: 4.5,
    reviews: 128,
    image: "/placeholder.svg?height=400&width=400",
    category: "iluminacion",
    subcategory: "linternas",
    isNew: false,
    inStock: true,
    date: "2023-09-05",
    technicalSpecs: {
      Potencia: "1000 lúmenes",
      LED: "CREE XP-L HD",
      Batería: "18650 recargable, 3000mAh",
      Autonomía: "2-20 horas según modo",
      Alcance: "300 metros",
      Resistencia: "IPX8 (sumergible 2m)",
      Material: "Aluminio aeronáutico T6061",
      Garantía: "5 años",
    },
    features: [
      "5 modos: Alto, Medio, Bajo, Estroboscópico, SOS",
      "Zoom ajustable para haz concentrado o difuso",
      "Carga por USB con indicador de nivel",
      "Clip de bolsillo reversible",
      "Base magnética para uso manos libres",
    ],
  },
]
